### ISSUE TITLE
Amortization Approach Specified in Attributes

### ISSUE THREAD

**Issue by rileyjenk** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#124]
### Type
> Type of issue (e.g. Dimension, Metric, Attribute, Documentation etc.)
Normalized? Yes | No

### Description
> Different providers may use differing methods to amortized costs. In the AmortizedCost metric we mention this but do not have any examples. 

### Definition of done

- [ ] We have examples of the different amortization approaches used by the providers
- [ ] The AmortizatedCost spec document is more clear on this topic.

**Comment by rileyjenk** [comment]
@flanakin here is the issue on your comments on the AmortizecCost metric.

**Comment by udam-f2** [comment]
@rileyjenk  If still relevant, could we please re-create this with the new feedback template?

**Comment by flanakin** [comment]
I believe this is resolved with ChargeSubcategory and the Discount handling attribute.
