### ISSUE TITLE
[Proposal] Add 'On Premises Private Cloud' ServiceCategory

### ISSUE THREAD

**Issue by iakov-aws** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#141]
### Type
> Dimension

### Proposed Change
> Add 'On Premises Private Cloud' ServiceCategory

### Context / Supporting information
> To cover non cloud products, for On Premises datacenters, like following:
> Azure Stack solutions, AWS Outpost, AWS MDC and Google Anthos (?).

**Comment by flanakin** [comment]
FYI - On-premises is currently covered by `Multicloud`.

> _"Support for interworking of multiple cloud and/or on-premises environments."_

**Comment by jpradocueva** [comment]
The description was copied to #379. TF1/2 agreed to close this issue on May 17.
