### ISSUE TITLE
Create a Billed Unit Price metric

### ISSUE THREAD

**Issue by ijurica** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#146]
### Type
> Type of issue: Metric
Normalized: No

### Description
> Define how Billed Unit Price (actual after-discount rate/unit price) should appear in cost data under metric.

### Definition of done

- [ ] Rationalize vendor-neutral, cross-cloud naming
- [ ] Complete spec template and include naming (code name, display name), constraints, guidelines, compatibility with major providers etc.

**Comment by udam-f2** [comment]
@ijurica  If still relevant, could we please re-create this with the new feedback template? Feels like we should close this out?

**Comment by ijurica** [comment]
As it is an outcome of various savings activities and can be derived from BilledCost/PricingQuantity (cake), I **suggest closing this one for now** and **focusing on Negotiated Unit Price or Negotiated Discount** (setting aside the naming aspect), which seems more crucial.
If necessary, we can revisit the BilledUnitPrice later (using the feedback template) 

@flanakin, as you expressed interest in this metric, I would like to confirm if it is acceptable to you?

**Comment by flanakin** [comment]
Why do we have to choose one over the other? Shouldn't we do both?

We've never closed on the ingredients vs. cake discussion, so I don't think that's a reason to exclude anything at this point.

**Comment by jpradocueva** [comment]
Task Force 2 agreed to close the issue on the May 15 call.
