### ISSUE TITLE
CommitmentUtilization column

### ISSUE THREAD

**Issue by flanakin** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#152]
Determine how unused commitments will be represented within the cost data. This may be in an existing column or a new column.

This column will be normalized so it is consistent across providers.

> ℹ️ _This column name is a placeholder and is not final._

**Comment by udam-f2** [comment]
@flanakin If still relevant, could we please re-create this with the new feedback template?

**Comment by flanakin** [comment]
This is completed with ChargeSubcategory for usage.
