### ISSUE TITLE
SKU term

### ISSUE THREAD

**Issue by flanakin** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#153]
### Type
> Dimension
> Normalized: No

### Description
> Define a column to indicate the term a commitment-based discount was purchased for (e.g., 1 year, 3 year, 5 year). Consider how this column might be used for other charges as well. We were able to identify that there are non-commitment charges that do have terms in some providers. Also consider whether there should be an associated period with the term.
> 
> Scenario: Commitment planning

### Definition of done

- [x] Rationalize vendor-neutral, cross-cloud naming
- [x] Complete spec template and include naming (code name, display name), constraints, guidelines, compatibility with major providers etc.

<br>

### Give it a 👍 below ↴

If you can discuss and help finalize the change, add yourself as an assignee ↗

Comments are welcome and encouraged!

**Comment by flanakin** [comment]
We decided to remove this column from 1.0 because the scenario that it was prioritized for (commitment planning) is more likely to use another data source to get the term.

**Comment by udam-f2** [comment]
@flanakin If still relevant, could we please re-create this with the new feedback template?

**Comment by ijurica** [comment]
Are we still considering the inclusion of SkuProperties and SkuPriceProperties columns, possibly in a key-value format? Alternatively, do we plan to introduce explicit columns for each relevant SKU and/or SKU Price property?

**Comment by flanakin** [comment]
I believe you're thinking of `SkuDetails` that was discussed in VS4 (cc @cnharris10). We should do that. But JSON should only be used for uncommon things that aren't primary factors in determining uniqueness of a SKU or for attributes that are only available for a small number of SKUs.

In this case, term is applicable to many SKUs and would be the one attribute that would differentiate possibly 3 SKUs (e.g., specific VM size+region reservation for 1- vs. 3- vs. 5-year commitment).

**Comment by ijurica** [comment]
> _Define a column to indicate the term a commitment-based discount was purchased for (e.g., 1 year, 3 year, 5 year)..._

What if a provider, for any reason, decides to associate more than one underlying SKU with a Commitment Discount? The term would apply to al of those SKUs, correct? 

Naming aside, I suggest moving this from `SKU` to the `Commitment Discounts` bucket (e.g., using CommitmentDiscountTerm instead of SkuTerm)

**Comment by ijurica** [comment]
Ignore my previous comment. I forgot about purchase-related SKUs :( , and I agree that in that case the 'SKU term'  is one of prominent SKU attributes that we should consider.

**Comment by shawnalpay** [comment]
Discussed in TF1 Oct 22 call. Will be represented in aggregate `Work Item` for SKU attributes.
