### ISSUE TITLE
SkuTier column

### ISSUE THREAD

**Issue by flanakin** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#155]
### Type

Constraint | Value
-- | --
Column type | Dimension
Column required | True
Allows nulls | True
Data type | String
Value format | Not specified

### Description

Define a column to identify the level a charge represents when tiered discounts or graduated pricing is applied.

### Definition of done

- [x] Rationalize vendor-neutral, cross-cloud naming
- [x] Complete spec template and include naming (code name, display name), constraints, guidelines, compatibility with major providers etc.

**Comment by udam-f2** [comment]
@flanakin If still relevant, could we please re-create this with the new feedback template?

**Comment by flanakin** [comment]
Updated

**Comment by flanakin** [comment]
Closing since I accidentally created another one for this already
