### ISSUE TITLE
Commitment-based discounts appendix

### ISSUE THREAD

**Issue by flanakin** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#159]
Document how the various columns and attributes work together to enable commitment-based discount scenarios, like chargeback, utilization, coverage, and savings.

**Comment by udam-f2** [comment]
@flanakin Could we please re-create this with the new feedback template.

**Comment by flanakin** [comment]
I'll close it for now, but if anyone feels this is important, please up-vote it and we can bring it back.
