### ISSUE TITLE
Discount types appendix

### ISSUE THREAD

**Issue by flanakin** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#160]
Document the different columns used to identify the different discount types and related scenarios, like rate verification and savings calculation.

**Comment by udam-f2** [comment]
@flanakin is there anything further needed here? If so, can you add. If not, can you close.

**Comment by flanakin** [comment]
I will defer this to practitioners. I'll close it for now, but if anyone feels this is important, please do up-vote it and we can bring it back.
