### ISSUE TITLE
PricingModel column

### ISSUE THREAD

**Issue by flanakin** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#161]
Define a column to identify the type of rate discount applied to a charge. For instance, this would be used to differentiate between on-demand usage and committed usage/cost.

This column will be normalized so it is consistent across providers.

> ℹ️ _This column name is a placeholder and is not final._

**Comment by udam-f2** [comment]
@flanakin Should we capture this in the new issue format and close this out?

**Comment by flanakin** [comment]
Completed with PricingCategory column
