### ISSUE TITLE
Create a Negotiated Unit Price metric

### ISSUE THREAD

**Issue by ijurica** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#164]
### Type
> Type of issue: Metric
Normalized: No

### Description
> Define how Negotiated Unit Price, which includes volume/tier-based reduction (same as List Unit Price) and negotiated discounts, should appear in cost data under metrics.

### Definition of done

- [ ] Rationalize vendor-neutral, cross-cloud naming
- [ ] Complete spec template and include naming (code name, display name), constraints, guidelines, compatibility with major providers etc.

**Comment by udam-f2** [comment]
@ijurica could you either add the necessary details based on the new template or close this and create a new one. Thanks!
