### ISSUE TITLE
Is there a particular target audience for the specification or a medium for consumption?

### ISSUE THREAD

**Issue by udam-f2** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#21]
### Description
Is the FOCUS specification targeting a particular audience? E.g. Finance? Eng? Different terminology may appeal to different groups

### Proposed approach
Spec and terminology should work for different data consumers (finance, eng, tooling vendors etc.) who consume via different mediums (direct programmatic access, access via tools / UI reports). If we appeal to one group or medium, we limit the usefulness. 

This will require us to strike a balance where we’re not being so generic where it becomes hard to use for the different use cases.

### Github issue or Reference
General spec-wide decision

**Comment by flanakin** [comment]
I could definitely see targeting specific personas or scenarios to scope 0.5 or even 1.0. I'm not thinking of that from a terminology perspective exactly, but more from a scoping perspective. The terminology we use must be understood by all personas. With that, we should probably include this in the naming standards to avoid persona-specific jargon that other personas may not understand. "Amortization" and "blending" are possibly good example of that.

**Comment by udam-f2** [comment]
Defined in the principles section of the specification.
