### ISSUE TITLE
CommitmentDiscountPlan column

### ISSUE THREAD

**Issue by flanakin** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#216]
Define a column to distinguish the provider name for the type of commitment-based discount (e.g., Reservation, Savings Plan, Resource-Based Committed Use Discount).

> ℹ️ _This column name is a placeholder and is not final._

**Comment by udam-f2** [comment]
@flanakin is this a duplicate of #162 ?

is there anything further needed here? If so, can you add. If not, can you close.

**Comment by flanakin** [comment]
This was resolved with CommitmentDiscountType
