### ISSUE TITLE
Adjustment Type column

### ISSUE THREAD

**Issue by flanakin** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#223]
Define a column to distinguish the different kinds of adjustments you will see coming from providers.

> ℹ️ _This column name is a placeholder and is not final._

**Comment by udam-f2** [comment]
@flanakin is there anything further needed here? If so, can you add. If not, can you close.

**Comment by flanakin** [comment]
This was resolved with ChargeSubcategory.
