### ISSUE TITLE
Attribute: Create a convention for a column naming scheme

### ISSUE THREAD

**Issue by udam-f2** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#23]
### Description
Discussion about if we should use snake, camel or pascal case for column id naming?

### Proposed approach
Pascal case has the most traction for use in column ids.

Normalized values (e.g. Service Category values like Compute, Developer Tools etc.) are the other place this could apply but since we're allowing spaces in that context so there's no need to apply this for those values.

### Github issue or Reference
General spec-wide decision

### Context
Column id is different from the display name which is a UI friendly name for a column. E.g. ResourceName (Column id) vs Resource Name (display name)

**Comment by flanakin** [comment]
My vote is for pascal-casing (EveryWordUppercased). Want me to take a stab at coming up with a proposal for column naming conventions? This would be good to review with everyone in a PR :-)

**Comment by mike-finopsorg** [comment]
There is nothing official from the Linux Foundation on this. I also vote for PascalCase as well for column naming.

**Comment by udam-f2** [comment]
Converting to issue for creating a new Attribute for column naming convention (not to be confused with column name spacing convention :) )
