### ISSUE TITLE
Create a Negotiated Cost metric

### ISSUE THREAD

**Issue by ijurica** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#237]
### Type
> Type of issue: Metric
Normalized: No

### Description
> Define how Negotiated Cost should appear in cost data under metrics.

### Definition of done

- [ ] Rationalize vendor-neutral, cross-cloud naming
- [ ] Complete spec template and include naming (code name, display name), constraints, guidelines, compatibility with major providers etc.

**Comment by flanakin** [comment]
This is a must-have!

I'd like to see this aligned to the existing terminology we have for pricing that is not committed (PricingCategory = "On-Demand"). Not everyone has negotiated discounts, so something that is more inclusive and consistent with what we already have would be ideal.

**Comment by ijurica** [comment]
This Cost would be used to **calculate savings based on negotiation activities**, by comparing it with the List Cost.
As @flanakin mentioned, we should also consider introducing the **corresponding unit price or discount**.

**Note:** 
Some time ago, we initiated the preparation of NegotiatedCost and NegotiatedUnitPrice metrics; however, we decided to put them on-hold at that point (refer to closed PRs #238 and #236).

**Comment by flanakin** [comment]
We should be clear that the value we use here is the price/cost when commitment discounts are not applied. It's the on-demand price/cost, which applies even when a negotiated discount is not applicable. It's not about negotiated discounts exclusively. We need to make sure the name of the columns is inclusive of all account types and doesn't imply that it's only about negotiated discounts.

**Comment by jpradocueva** [comment]
@ijurica will link the Issue to the PR and the group, TF-2,  agreed to close the Issue (on May 15)

**Comment by ijurica** [comment]
Addressed in PR #364.
