### ISSUE TITLE
How do we write the acronym Id for various dimensions where necessary

### ISSUE THREAD

**Issue by udam-f2** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#24]
### Description
Do we write ID or Id or not use acronym and write Identifier where its needed in naming for a dimension (e.g. ResourceID vs ResourceId vs ResourceIdentifier)

### Proposed approach
Use ID where both letters are upper case. 
Supporting evidence: [stackexchange discussion](https://english.stackexchange.com/questions/101248/how-should-the-abbreviation-for-identifier-be-capitalized )

### Github issue or Reference
General spec-wide decision

**Comment by flanakin** [comment]
My vote is to use `Id` in identifiers, like column names, and `ID` in strings, like display names. Should we create a poll for this in discussions?

**Comment by udam-f2** [comment]
Defined in column naming convention.
