### ISSUE TITLE
Should billing data come with a schema document that provides information about the columns data types/lengths?

### ISSUE THREAD

**Issue by udam-f2** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#26]
### Description
Should there be a FOCUS attribute that describes the need for the schema of the data (FOCUS columns and optionally vendor columns). This informs people trying to ingest/analyze the data to know the data types / lengths of the columns in the data.

Does the column lengths for data need to be the same for all providers (and therefore are just a part of the spec)? OR should that be up to the provider - as long as they publish the schema. Consumers would need to adjust based on the providers they're using and pick the longest length.

### Proposed approach
Yes, schema should be defined and made available by providers. They describe the columns and the data types/lengths. Lengths are up to the vendor but should be published with their schema. 

Versioned schema info should be available via a well-known location on the web OR provided along with the billing datasets.

### Github issue or Reference
General spec-wide decision

### Context
Based on feedback, if we think this should be a part of the spec as an attribute, we need to create a Task for it and assign to a version. If lengths are governed by the specification, then the template needs to be beefed up beyond the current 'Data type' section.

**Comment by ijurica** [comment]
as the schema document is also the starting point for data validation criteria (#27), it would be very useful to specify whether the data (dimensions or metrics) is mandatory (depending on the charge type). I'm not sure if this has already been covered.

**Comment by flanakin** [comment]
I would expect there to be a baseline schema from FOCUS for every customer/product to use when they support the specific schema version. I'd love to see schemas for vendor customizations, but not sure if we should make that required for everyone who emits FOCUS data. I see it being highly recommended, just not sure about making it required. Curious what others think.

**Comment by rileyjenk** [comment]
If there is any room for schemas to differ...which I believe there is, there should be a metadata object/call/file/thing that can be pulled. If for example, the FOCUS data is delivered via data artifacts (files in csv, their should be included headers or a metadatafile that is periodically available representing the schema, especially on change.

**Comment by flanakin** [comment]
Should this be closed with metadata?

**Comment by jpradocueva** [comment]
The group decided to close it on the May  28 call. It is covered by the metadata.
