### ISSUE TITLE
Attribute: Data granularity for usage cost

### ISSUE THREAD

**Issue by udam-f2** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#29]
Define the attributes / characteristics of 'usage' costs with regards to time granularity, resource level billing etc. There is a separate task to define this for non-usage attributes (e.g. taxes, fees etc.) where the cost is not or may not be directly attributed to an individual resource.

**Comment by rileyjenk** [comment]
See comments on https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/122 concerning implications of a broader time granularity definition in the spec.
