### ISSUE TITLE
Review the UsageQuantity metric

### ISSUE THREAD

**Issue by ijurica** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#294]
### Type
> Type of issue: Metric

#### Consider rephrasing current Usage Quantity definition and description.

Current definition of the Usage Quantity:
> The Usage Quantity represents the volume of a given resource or service used or purchased based on the [Usage Unit](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/blob/working_draft/specification/columns/usagequantity.md#usageunit)...

Does Usage Quantity represent **...the volume of a given resource or service...** or **...the volume of a given SKU associated with a resource or service...**?

_NOTE: Applies to Usage Quantity as well_

#### Review the normative paragraph

Current version:

> ... The value MAY be negative in cases where [ChargeSubcategory](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/blob/working_draft/specification/columns/usagequantity.md#chargesubcategory) is "Refund". This column MUST NOT contain null values when [SkuPriceId](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/blob/working_draft/specification/columns/usagequantity.md#skupriceid) is not null.

- What do we expect/allow in UsageQuantity column when ChargeCategory is "Purchase"? Reminder: SkuPriceId MUST NOT be null in case of "Purchase". Not sure if this applies to UsageQuanty.
- Consider something like ths: _... MUST NOT be null when ChargeCategory is "Usage" or  ChargeSubcategory is "Refund", related to usage-based charges ..._
- Consider defining conditions for when it MUST be null and MUST NOT be null.
- Consider aligning UsageQuantity and UsageUnit normative

_NOTE: Review Usage Unit normative as well_

**Comment by flanakin** [comment]
Makes sense. It's about usage of the SKU. Same goes for purchases. Purchases should all map to a SKU in the same way that usage maps to a SKU. Otherwise, how will purchases have a price-point? Seems like `MUST NOT be null when ChargeCategory is "Purchase"` is also needed.

**Comment by aqu-erp** [comment]
Covering #293 as well. 
If there is a record for a purchase, then by nature of it having a record, it should have a usagequantity. 
Depending on the nature of bundling or packaging by a seller, the purchase can have a `pricingquantity` of 1 or many. Consequently, the `usagequantity` must be present but also be dynamic to then reflect the actual nature of the purchase. 

Ex: Purchase of 50 licenses, bundled for a flat price per group of 5. 
`chargeCategory == Purchase`
`pricingQuantity == 5`
`usageQuantity == 10`

**Comment by mike-finopsorg** [comment]
Lets add examples of how this looks across the main Quantity columns in this document https://docs.google.com/spreadsheets/d/1z1DFBAVx3um_OIAGTzYVl_BEMJMha90pRPa5mKrietE/edit#gid=0

**Comment by ijurica** [comment]
Adding key parts of  a recent slack conversation (#wg-focus-converters) as feedback regarding the ambiguity surrounding the distinction between UsageUnit - UsageQuantity and PricingUnit - PricingQuantity pairs, for further consideration...

> _In its simplest form UsageQuantity = PricingQuantity when they have the same unit and don't use block pricing. I always use this example to explain the two..._
>
> EA can have VM compute time charged in blocks of 100 hours. In this case, you'll see UnitOfMeasure = "100 Hours". Let's say you have 24 hours of compute. This is what we did in our FOCUS dataset...
> 
> - UsageQuantity = 24
> - UsageUnit = "Hours"
> - PricingQuantity = 0.24
> - PricingUnit = "Hours"
> - x_PricingBlockSize = 100
> - x_PricingUnitDescription = "100 Hours" = UnitOfMeasure

> ok this makes sense, Thanks :+1:. We should maybe update these Focus column specification md files with this example, at the moment they don’t explain this too well (for me at least)

**Reminder:** Don't forget to incorporate this example into the supporting content of the relevant columns.

**Comment by ijurica** [comment]
Dear Assignees :),

1. Please review and provide your feedback regarding the nullability of UsageQuantity and UsageUnit for various ChargeCategory - ChargeSubcategory combinations available in the [Google Spreadsheet](https://docs.google.com/spreadsheets/d/1z1DFBAVx3um_OIAGTzYVl_BEMJMha90pRPa5mKrietE/edit#gid=0).

3. If you agree with the suggested NULL/NOT NULL use cases, please provide suggestions on how to improve the proposal for the Usage Quantity specification below. I'm sure the phrasing can be improved (note: modifications to the spec highlighted in bold)

>The Usage Quantity represents **the volume of a given SKU associated with a resource or service** used or purchased based on the Usage Unit. Usage Quantity is often derived at a finer granularity or over a different time interval when compared to the Pricing Quantity (complementary to Pricing Unit), and focuses on resource and service consumption, not pricing and cost.
>
>UsageQuantity MUST be present in the billing data. This column MUST be of type Decimal and MUST conform to Numeric Format. The value MAY be negative in cases where ChargeSubcategory is "Refund". 
>
>**This column MUST NOT be null under the following conditions:**
>
> - **When ChargeCategory is "Usage" and ChargeSubcategory is "On-Demand" or "Used Commitment".**
> - **When ChargeCategory is “Adjustment” and ChargeSubcategory is "Refund", related to charges with a specific SkuPriceId.**
>
> **This column MUST be null in case of any other ChargeCategory – ChargeSubcategory combinations.**


Thank you.

**Comment by aqu-erp** [comment]
> 
> > _In its simplest form UsageQuantity = PricingQuantity when they have the same unit and don't use block pricing. I always use this example to explain the two..._
> > EA can have VM compute time charged in blocks of 100 hours. In this case, you'll see UnitOfMeasure = "100 Hours". Let's say you have 24 hours of compute. This is what we did in our FOCUS dataset...
> > 
> > * UsageQuantity = 24
> > * UsageUnit = "Hours"
> > * PricingQuantity = 0.24
> > * PricingUnit = "Hours"
> > * x_PricingBlockSize = 100
> > * x_PricingUnitDescription = "100 Hours" = UnitOfMeasure
> 


In a FOCUS-native dataset, would `PricingUnit` still be `== "Hours"`? Or should the supporting content show `== "100 Hours"`? Forgive me for being extra dense, my math isn't mathing. If in the above scenario `listcost` or `billedcost` increase only when additional blocks are reached...

Then for a static`ListUnitPrice` per single `Pricing Unit`, `PricingQuantity` and `PricingUnit` must be the quantity of blocks, no?


Specification columns referenced below:

>List Cost represents the cost calculated by multiplying [List Unit Price](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/blob/working_draft/specification/columns/listcost.md#listunitprice) and the corresponding [Pricing Quantity](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/blob/working_draft/specification/columns/listcost.md#pricingquantity).

and 

>The List Unit Price represents the suggested provider-published unit price for a single [Pricing Unit](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/blob/working_draft/specification/columns/listunitprice.md#pricingunit) of the associated SKU, exclusive of any discounts.

**Comment by udam-f2** [comment]
Open for feedback on the spreadsheet linked below

> Dear Assignees :),
> 
> 1. Please review and provide your feedback regarding the nullability of UsageQuantity and UsageUnit for various ChargeCategory - ChargeSubcategory combinations available in the [Google Spreadsheet]

**Comment by thecloudman** [comment]
Id like to add my thoughts on this. When I look at my data in Azure, Pricing QTY and Usage QTY are almost exactly the same. I have found a few lines where Pricing QTY is different to Usage QTY for the majority (more than 95%) of my data Usage QTY and Pricing QTY are identical. Why would we have two columns with the same data? When looking at pricingblocksize and comparing usage QTY and Pricing QTY, blocksize has no direct impact on qty? I would have thought to get a true representation of list price you would use lits unit price multiplied by Usage QTY. You wouldn't be able to compare list price to effective price or billed price if list price used a different QTY metric.

**Comment by flanakin** [comment]
> In a FOCUS-native dataset, would `PricingUnit` still be `== "Hours"`? Or should the supporting content show `== "100 Hours"`?

Do we want to tackle PricingUnit here? Happy to. Just want to confirm before I jump in 😜

**Comment by thecloudman** [comment]
> Id like to add my thoughts on this. When I look at my data in Azure, Pricing QTY and Usage QTY are almost exactly the same. I have found a few lines where Pricing QTY is different to Usage QTY for the majority (more than 95%) of my data Usage QTY and Pricing QTY are identical. Why would we have two columns with the same data? When looking at pricingblocksize and comparing usage QTY and Pricing QTY, blocksize has no direct impact on qty? I would have thought to get a true representation of list price you would use lits unit price multiplied by Usage QTY. You wouldn't be able to compare list price to effective price or billed price if list price used a different QTY metric.

UPDATE - I have logged a bug with exports team at Microsoft around issues with Pricing QTY and Usage QTY being the same value, as apparently these should be different.

**Comment by ijurica** [comment]
SUGGESTIONS:

- Limit the scope of this high-prio spec change to address:
    - Rephrasing `...volume of a given resource or service...` to `...volume of a given SKU associated with a resource or service...`
    - Reviewing the normative paragraph for UsageUnit and UsageQuantity
      See [Google Spreadsheet](https://docs.google.com/spreadsheets/d/1z1DFBAVx3um_OIAGTzYVl_BEMJMha90pRPa5mKrietE/edit#gid=0). for various ChargeCategory - ChargeSubcategory combinations.
      The current suggestion outlined below
    
      >This column MUST NOT be null under the following conditions:
      >- When ChargeCategory is "Usage" and ChargeSubcategory is "On-Demand" or "Used Commitment".
      >- When ChargeCategory is “Adjustment” and ChargeSubcategory is "Refund", related to charges with a specific SkuPriceId.
      > <br>
      > This column MUST be null in case of any other ChargeCategory – ChargeSubcategory combinations.

- Create a separate Issue/Proposal and an additional Sheet (with extra columns and sample data, featuring actual numbers) to discuss:
  - Difference between UsageUnit and PricingUnit
  - Block-pricing clarification and sample data
  - And perhaps even reopen the PricingUnit discussion, as Michael suggested :)

**Comment by udam-f2** [comment]
For the member meeting discussion today, if we're using usage quantity and usage unit for things that aren't actually consumption (e.g. unused commitments, credits), this would be the part to update:

"Usage Quantity is often derived at a finer granularity or over a different time interval when compared to the [Pricing Quantity](#pricingquantity) (complementary to [Pricing Unit](#pricingunit)), and focuses on *resource* and *service* **consumption**, not pricing and cost."

**Comment by ijurica** [comment]
For further discussions/progress on this issue:

- For definition and nullability updates check out the corresponding PR #324.
- For clarification on PricingUnit vs UsageUnit and block-pricing, including sample data refer to the additional Discussion topic/Proposal #327.

**Comment by ijurica** [comment]
Related PR (#324) successfully closed.
