### ISSUE TITLE
Should AZ be a required column?

### ISSUE THREAD

**Issue by cnharris10** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#297]
### Description
> Describe the discussion topic and/or open topic is. Describe discussion that has taken place and where community feedback is needed. Provide specifics (specially if there are multiple possible options).

<img width="1437" alt="image" src="https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/assets/17853509/899eee66-f97e-4bb5-97de-b6e5b253e0b4">
<img width="1096" alt="image" src="https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/assets/17853509/13ad4b40-d16c-4a6f-92a4-e8870087d0b8">

### Proposed approach
> Describe the approach that your group is proposing

### Github issue or Reference
> If the topic is related to a particular work item, reference the Github issue. If its a specification-wide topic, indicate that.

### Context
> Add any context that may help the community think through this and provide useful feedback

**Comment by flanakin** [comment]
If I remember correctly, AvailabilityZone is optional because not all providers support the concept and it doesn't impact cost.

If we make this required, are we making a statement that there should not be any optional columns? Should we define principles for when columns should or should not be optional/required?

**Comment by rupagcp** [comment]
Agree that we should have principles for which fields are "required" and why. Not all Cloud providers have other fields, yet they are marked as "required". I was just confused how we collectively decided on this one as not required when I saw all other fields required. How do we move forward in this discussion to make a decision? Thanks in advance

**Comment by udam-f2** [comment]
I think this is related to #296. The direction we go on that issue should help us decide if columns that (some|most) providers don't support can be made to column required: False 

Commitment discounts aren't supported by many providers. Are those columns required? 

It feels like we're narrowing in on a bare minimum set that's required (dates, provider, pricing quantity, list unit price, list cost, billed cost, currency and another set that based on having detailed billing data may be provided.

**Comment by flanakin** [comment]
Should we mark this as for 1.0 but dependent on #296?
