### ISSUE TITLE
[Proposal] "Billing Account" term and description confusion

### ISSUE THREAD

**Issue by flanakin** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#300]
### Type
> Dimension: BillingAccountId/Name
> _A Billing Account ID is a provider assigned identifier for a billing account. Billing accounts are commonly used for scenarios like grouping based on organizational constructs, invoice reconciliation and cost allocation strategies._

Glossary:
> _A container for resources and/or services that are billed together in an invoice. A billing account may have sub accounts, all of whose costs are consolidated and invoiced to the billing account._

### Description
> During internal discussions, several people felt the term and description for "billing account" wasn't explicit enough about being the scope at which an invoice is generated.
>
> I haven't talked to practitioners yet, but I'm especially interested in hearing about this confusion for Microsoft customers who may be used to the term "billing account" being used to be the top-level account and not where the invoice is generated. I'm not sure if other clouds support the flexibility of having a parent scope with lower-level invoice scope where "billing account" means something different.
>
> Side note: From a usability perspective, the first reference to a glossary term should probably be linked to the glossary. Currently, the terms are just italicized. Ideally, we would also be able to navigate through the GitHub repository as well to help contributors work more efficiently.

### Definition of done
- [x] Rationalize vendor-neutral, cross-cloud naming
- [x] Complete spec template and include naming (code name, display name), constraints, guidelines, compatibility with major providers etc.

<br>

### Give it a 👍 below ↴

If you can discuss and help finalize the change, add yourself as an assignee ↗

Comments are welcome and encouraged!

**Comment by udam-f2** [comment]
Could we split the issue into two here? 

One is about billing account naming (which we went through a long exercise previously and settled on given that there weren't any better options - but happy to hear other options). The other is for formatting improvements.

**Comment by flanakin** [comment]
Makes sense. I didn't want to add even more issues 🙃 The linking should probably just be a PR unless there was a reason we didn't want to do that. I just mentioned that since I had to work harder to find the glossary definition.

The point of this issue was primarily the billing account description but I would love to hear from practitioners about the name confusion.

**Comment by ahullah** [comment]
Discussed on TF1 meeting .... proposal agreed to just add a link to 'Billing Account' definition in glossary. This supports future ease of maintainability (as these definitions may be referenced in multiple documents) will wait for further practitioner feedback on if expansion of the definition in BillingAccountId/Name.md is necessary.

**Comment by ahullah** [comment]
Amusingly the 'glossary' type links dont seem to work as hyperlinks.... is there another change needed here?

**Comment by jpradocueva** [comment]
The group concluded that the description in the glossary is good enough. There is no bug that the links don't work in GitHub. This topic will be reviewed again in the future. This applied to the links in general.
