### ISSUE TITLE
[Proposal] Region display name vs. ID

### ISSUE THREAD

**Issue by flanakin** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#304]
### Type
> Dimension
> Normalized: No

### Description
> Most FOCUS columns use a display name. Should the Region column also use a display name? Providers have both an ID and a display name. Should we have a separate RegionId and RegionName columns?
>
> Not sure if this should be a spec change or discussion topic. Tracking it as a spec change, but expecting a discussion to determine if we think this makes sense.

### Definition of done
- [x] Rationalize vendor-neutral, cross-cloud naming
- [x] Complete spec template and include naming (code name, display name), constraints, guidelines, compatibility with major providers etc.

<br>

### Give it a 👍 below ↴

If you can discuss and help finalize the change, add yourself as an assignee ↗

Comments are welcome and encouraged!

**Comment by mike-finopsorg** [comment]
+1, this has been a pain point for me as a practitioner previously when trying to join data (e.g. Billing with API) with one set only containing the Id and the other only a Name, having both will remove this friction for practitioners.

**Comment by udam-f2** [comment]
Feels like a high-priority item given the backward compatibility impact.
FYI @salpaysenturus who originally called out inconsistencies in the naming convention for this too.

**Comment by marc-perreaut** [comment]
From data efficiency & simplicity perspective, I would prefer to have a single column, which serves as both display name and ID.
I am not sure why providers have the need to have both display name and ID?

**Comment by rupagcp** [comment]
Shouldn't region name be a unique identifier?

**Comment by cnharris10** [comment]
Discussed in the maintainer's meeting.  This column is meant to be the Region's ID and should be renamed to RegionId.  We should discuss whether a RegionName makes sense to add as well

**Comment by ilia-semenov** [comment]
PR for adding Region ID: [PR-352](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/352)
