### ISSUE TITLE
[Proposal] Confusing information hierarchy for usage and commitment discounts

### ISSUE THREAD

**Issue by flanakin** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#306]
### Type
> Dimension: ChargeSubcategory 
> Normalized: Yes
>
> Related dimensions: ChargeCategory, PricingCategory 

### Description
> Here's what the information hierarchy looks like for usage data:
> * ChargeCategory = `Usage`
>   * ChargeSubcategory = `Other`
>   * ChargeSubcategory = `Used Commitment`
>   * ChargeSubcategory = `Unused Commitment`
>     * PricingCategory = `Commitment-Based Discount`
>       * PricingSubcategory (proposed) = `Committed Usage`
>       * PricingSubcategory (proposed) = `Committed Spend`
>       * PricingSubcategory (proposed) = `Other`
>
> From an information architecture perspective, this is confusing because we're declaring a commitment as used or unused before we say the usage is related to a commitment. I'm also not sure if used vs. unused commitment is the logical, next level breakdown of a Usage charge. I wonder if there's a better breakdown for the type of Usage charge and if it would be better to move used vs. unused commitment to another column.
>
> We also need to revisit the descriptions for `Used Commitment` and `Unused Commitment` to ensure they're inclusive of all commitments and not just commitment discounts (e.g., capacity reservations that don't have a discount but do have a penalty). 

### Definition of done
- [x] Rationalize vendor-neutral, cross-cloud naming
- [x] Complete spec template and include naming (code name, display name), constraints, guidelines, compatibility with major providers etc.
- [x] Include principles and governance criteria for maintaining this dimension

**If Normalized Dimension**
Work for generating the normalized list of supported values is tracked in a separate issue. Mappings between normalized values and vendor specified values need to be explored as a part of this work. However, these mappings are not included in the spec documentation. Separate tasks will be created for making these mappings available to practitioners outside of the FOCUS repository.

<br>

### Give it a 👍 below ↴

If you can discuss and help finalize the change, add yourself as an assignee ↗

Comments are welcome and encouraged!

**Comment by gparker-at-sf** [comment]
Some thoughts from reviewing: 
- Agree, the requirement for amortization is unusually specific; it's not clear to me that it's necessary but it's specific enough and mentioned twice so there seems to be a reason it was included. 
- For commitment discounts, it's my understanding that the heirarchy of commitmentdiscount exists to support the requisite metadata to identify the specific commitment; capacity reservations (which dont provide a discount but do provide a penalty) would benefit from a similar treatment; I don't see how else to identify the specific reservation in the spec. 
- The description in ChargeSubCategory for Unused Commitment seems sufficient vague (the example doesnt imply that this is the only valid reason to have an unused commitment). 

Possibly unrelated but occurred to me while reading the relevant spec, as it seems surprising these are required to be null:
- Should there be a Charge Subcategory for Purchases to reflect one-time or subscriptions?
- Should there be a Charge Subcategory for Tax to reflect it's nature? 

Happy to discuss further!

**Comment by flanakin** [comment]
> Should there be a Charge Subcategory for Purchases to reflect one-time or subscriptions?

We discussed this. While I do feel like that logically makes sense as a breakdown of purchases, we felt like ChargeSubcategory was a better name for that column. If we move it into ChargeSubcategory, we're removing a bit of clarity in the purpose of the column.

**Comment by flanakin** [comment]
The main purpose of this issue (for me) was to determine if the values in our normalized columns align with the information hierarchy of the columns' intents.

If the information hierarchy is:

1. ChargeCategory
2. ChargeSubcategory
3. PricingCategory
4. PricingSubcategory (if/when it comes in)

Does that make sense with these values?

1. Usage
2. Used Commitment
3. Commitment-Based Discount
4. Committed Usage

Asking another way would be: When you think of all possible "Usage" records, what are the top-level ways you would want to categorize them to understand what kinds of usage they represent? Is that by whether or not they were committed and if those commitments were used? I feel like there's most likely another breakdown of usage that would be more useful. And if that is the case, we should move "Used Commitment" to a separate column.

**Comment by gparker-at-sf** [comment]
The use case I'm using to evaluate these questions is On-Demand Capacity Reservations. I think the current model breaks down at the PricingCategory, unless we abuse 'Other'.

**Comment by flanakin** [comment]
I'll add that to the list of scenarios. Capacity reservations would have `PricingCategory = "On-Demand"` assuming there's no commitment discount associated. We didn't include "Discount" in "Used Commitment" and "Unused Commitment" to support capacity reservations, but there isn't any other column to indicate the capacity reservation ID. That's the one gap I'm aware of.

I'd like to keep capacity reservations out of this if we can only because I worry that will cause a bunch of other conversations that could delay a more critical decision point. If we feel capacity reservations are required to move forward, then let's work thru that.

**Comment by gparker-at-sf** [comment]
Could you clarify what you mean by keeping capacity reservations 'out of this?'

**Comment by ijurica** [comment]
So, does the following apply for Capacity reservations (assuming there are no commitment-based discounts):

- ChargeCategory: `Purchase`
- ChargeSubcategory: _ongoing discussion_
- PricingCategory: `On-Demand`
- PricingSubcategory: `Other` **???**

Is introduction of an additional PricingSubcategory value for this purpose an option?

**Comment by flanakin** [comment]
> Could you clarify what you mean by keeping capacity reservations 'out of this?'

I just meant not part of the information hierarchy conversation but as a separate topic to be tracked independently. But we decided to merge this issue with a few others, so I added it to the larger bucket. My only concern was about taking too long to close things.

**Comment by flanakin** [comment]
Consolidating this with other charge/pricing categorization issues to discuss together.

@gparker-at-sf please move 👍 vote to #330
