### ISSUE TITLE
[Proposal] SKU tier

### ISSUE THREAD

**Issue by flanakin** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#312]
### Type
> Dimension: `SkuTier` or `SkuPricingTier`
> Normalized: No

### Description
> Add an ability to identify which tier is being used. 1.0-preview does not have any way to identify tiered pricing. All tiered pricing should be easily identifiable (e.g., PricingSubcategory = Tiered) and offer the ability to separate each tier (e.g., SkuTier = "\<provider-specific-value>". 

### Definition of done
- [x] Rationalize vendor-neutral, cross-cloud naming
- [x] Complete spec template and include naming (code name, display name), constraints, guidelines, compatibility with major providers etc.

<br>

### Give it a 👍 below ↴

If you can discuss and help finalize the change, add yourself as an assignee ↗

Comments are welcome and encouraged!

**Comment by mike-finopsorg** [comment]
Would you need a SkuTier if the SKUPricingId pointed towards the price that was charged?

**Comment by marc-perreaut** [comment]
Identifying pricing tiers is useful to understand the pricing structure and threshold effects.
Maybe `SkuPricingTier` is more explicit than `SkuTier`, as the pricing of the SKU is tiered, not the SKU itself.

**Comment by flanakin** [comment]
> Would you need a SkuTier if the SKUPricingId pointed towards the price that was charged?

The finance team would because they don't have the ability to join these two extremely large datasets. If FOCUS is intended to be approachable and usable by anyone to answer questions about tiered pricing, then it would need to be in this dataset. I suppose the question is whether or not getting cost per specific tier is one of those scenarios.

> Next to SkuPricingTier we might consider introducing a PricingModel / PricingStrategy / PricingApproach column to indicate the pricing approach.

This is covered by [PricingSubcategory](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/308) 🙂

**Comment by shawnalpay** [comment]
Discussed in TF1 Oct 22 call.  Will be represented in aggregate `Work Item` for SKU attributes.
