### ISSUE TITLE
Provider SKU size 

### ISSUE THREAD

**Issue by flanakin** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#313]
### Type
> Dimension
> Normalized: No

### Description
> FOCUS needs a way to identify what actual product SKU was used by name. This would be something like the VM "size" or "shape" or whatever term each provider uses to define it. Maybe something like `SkuType`?

### Definition of done
- [x] Rationalize vendor-neutral, cross-cloud naming
- [x] Complete spec template and include naming (code name, display name), constraints, guidelines, compatibility with major providers etc.

<br>

### Give it a 👍 below ↴

If you can discuss and help finalize the change, add yourself as an assignee ↗

Comments are welcome and encouraged!

**Comment by marc-perreaut** [comment]
If this is about naming the SKU with a user-friendly name compared to the `SkuId`, why not simply `SkuName`?

I believe a `SkuType ` would be over-arching the `SkuName `. For example, `SkuType`  would be the VM series/family, while the `SkuName ` would be the VM series/family for a given size (number of VCPUs).

**Comment by flanakin** [comment]
The "SKU" in FOCUS terminology is more than just the size/shape of a VM, as an example. So the SkuName would be something that would represent the entire SKU, which includes things like region, size, etc. I referred to it as "SKU type" because I was trying to make it an attribute of the SKU. There may be a better name. That should be part of the convo.

**Comment by jpradocueva** [comment]
### Action Items:
- [ ] TS2-[#313](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/313)-[#314](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/314): Michael: To provide a list of SKU attributes and further expand on what constitutes a SKU ID.
- [ ] TS2-[#313](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/313)-[#314](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/314): All Members: To prepare for a detailed discussion on SKU attributes and categorization next week.
