### ISSUE TITLE
Add Support Service Category

### ISSUE THREAD

**Issue by yprikhodko** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#321]
### Type
> Type of issue (e.g. Dimension, Metric, Attribute, Documentation etc.)
Normalized? Yes | No
Yes
Dimension
### Description
> Description of the issue
Add new Service Category value Support to allow practitioners to easily distinguished support related charges from workload related charges

### Definition of done

- [ ] Rationalize vendor-neutral, cross-cloud naming
- [ ] Complete spec template and include naming (code name, display name), constraints, guidelines, compatibility with major providers etc.
** If Normalized Dimension **
- [ ] Include principles and governance criteria for maintaining this dimension

Suggested PFR  - https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/251 

** If Normalized Dimension **
Work for generating the normalized list of supported values is tracked in a separate issue. Mappings between normalized values and vendor specified values need to be explored as a part of this work. However, these mappings are not included in the spec documentation. Separate tasks will be created for making these mappings available to practitioners outside of the FOCUS repository.

**Comment by thecloudman** [comment]
Agree - Support should be a service category, however Microsoft do not include support in usage data from what i have seen. Other CSP's do. Would need to ensure CSP's can include this when support is purchased outside of the CSP plan as well.

**Comment by jpradocueva** [comment]
@yprikhodko, if we want to incorporate this content in release 1.0, we need a PR on this topic by this Thursday, April 18, for discussion and to be agreed by no later than April 25.

**Comment by jpradocueva** [comment]
@yprikhodko This issue needs to be driven by someone in order to make the cut on April  25. Otherwise, the topic will be moved to v1.1.

**Comment by jpradocueva** [comment]
The maintainers agreed to move this topic to release v1.1 as no PR has been presented for discussion.

**Comment by ijurica** [comment]
The description was copied to #379. TF1/2 agreed to close this issue on May 17.
