### ISSUE TITLE
Clarification on PricingUnit vs UsageUnit, block-pricing, and inclusion of sample data for relevant use cases

### ISSUE THREAD

**Issue by ijurica** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#327]
### Description
> Conversation in #wg-focus-converters slack channel and further discussion among focus-members indicates that we should 
> - provide more clarity on distinction between UsageUnit and PricingUnit
> - provide more clarity on block-pricing
> - provide sample data for block-pricing and other relevant use cases (e.g. stairstep pricing)

### Proposed approach
> We should at least discuss and address previously mentioned issues as part of PricingUnit supporting content

### Github issue or Reference
> Discussion on the subject began in issue #294. It was decided to maintain the original scope of #294 and open an additional (this) issue to address this specific purpose.

**Comment by jpradocueva** [comment]
The group agreed to copy the description to #440 and close this Issue.
