### ISSUE TITLE
Charge and Pricing category cleanup

### ISSUE THREAD

**Issue by flanakin** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#330]
📅 _**NOTE:** This issue merges issues #305, #306, and #308 and will be discussed together in Task Force 2 on Wednesdays at 9pm UTC._

### Type

> Dimension: ChargeSubcategory, PricingSubcategory
> Normalized: Yes
>
> Related dimensions: ChargeCategory, PricingCategory

### Description

> This issue is consolidating change requests across 3 areas:
> - ChargeSubcategory values
> - Commitment utilization
> - Pricing categorization

#### ChargeSubcategory

> **Context:** [ChargeSubcategory](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/blob/working_draft/specification/columns/chargesubcategory.md) represents the highest-level breakdown of a specific type of charge.
> 
> **Definition:** _Charge Subcategory indicates what kind of usage or adjustment the row represents. Charge Subcategory is a supplemental detail to the Charge Category). It provides additional context to describe the primary category of charge._
>
> Scenarios:
>
> 1. ☑️ **What is the highest-level breakdown of usage charges?**
>    In 1.0 preview, we decided to indicate whether or not a commitment was applied and used as that highest-level breakdown. But is that right? Should there be a different breakdown of usage that is more about the usage itself than whether a commitment discount was applied or not? This is important for GA because if we agree that there is a better breakdown, we should move "Used Commitment" and "Unused Commitment" to a different column. We do not need to finalize what goes into ChargeSubcategory right now if we do this. But we should make that decision before GA.
>
>    **Definition:** _When Charge Category is "Usage" and the charge is related to a commitment, the Charge Subcategory indicates whether the row represents committed usage or is an amortized charge for the unused portion of the commitment. Charge Subcategory is commonly used for scenarios like calculating commitment utilization when Charge Category is "Usage"._
>
>    Example information hierarchy based on current ChargeSubcategory values:
>    * ChargeCategory = `Usage`
>      * ChargeSubcategory = `On-Demand`
>      * ChargeSubcategory = `Unused Commitment`
>      * ChargeSubcategory = `Used Commitment`
>        * PricingCategory = `Commitment-Based`
>
>    💡 _**Proposal:** Move “Used Commitment” and “Unused Commitment” to a dedicated column (name TBD). Leave ChargeSubcategory as null for usage and revisit the best breakdown of usage after breaking changes are finalized._
>
>    ⚖️ _**Decision:** We did not have a clear idea of what this should be and decided to move “Used Commitment” and “Unused Commitment” to a dedicated column and revisit based on feedback post-GA._
>
> 2. ❌ **What is the highest-level breakdown of purchase charges?**
>    Some ideas:
>    1. Whether or not you’ll see more charges::
>       - One-Time
>       - Recurring
>    2. What kind of thing was purchased:
>       - Cloud Service = Native service offerings from the provider
>       - Marketplace = Third-party service offerings through the provider's marketplace
>       - Commitment Discount = Commitment discount purchases
>       - Support = Technical support from the provider
>       - Professional Services = Consulting, etc.
>    3. Combination of both:
>       - CommitmentRecurringFee
>
>    💡 _**Proposal:** Discuss ChargeSubcategory for purchases with usage after we finalize the breaking changes for GA._
>
>    ⚖️ _**Decision:** We did not have a clear idea of what this should be and decided to revisit based on feedback post-GA._
>
> 3. ☑️ **How should adjustments be represented?**
>    ChargeSubcategory supports "Refund", "Credit", "Rounding Error", and “General Adjustment” for adjustments. Should credits be grouped with other "adjustments"? Should refunds be attributed to usage and purchases separately? This is slightly more explicit about its intent, which is nice, but is inconsistent with all the other scenarios where we represent unhandled scenarios. Do we need to differentiate "Rounding Error" and “General Adjustment”?
>
>    💡 _**Proposal:** Rename “General Adjustment” to “Other” and add a rule to the Column naming attribute that requires *Category and *Subcategory columns to include an “Other” option._
>
>    ⚖️ _**Decision:** Credits will move to ChargeCategory, Refund will move to a new ChargeClass column, and we'll remove ChargeSubcateogry for GA. We can revisit the breakdown of charges based on feedback post-GA._
>
> 4. ❌  **Should bulk and single refunds be split to clarify when SkuPriceId is required?**
>    All refunds are identified by `ChargeSubcategory == “Refund”`. The way to identify refunds for a single charge is when SkuPriceId is not null. When SkuPriceId is null, then that refund is implicitly a bulk refund. Do practitioners need to aggregate all single and bulk refunds together with a single filter? Is a “not null” check adequate for identifying bulk refunds? Should FOCUS force/nudge providers to avoid bulk refunds?
>
>    💡 _**Proposal:** Split “Refund” into separate “SKU Refund” and “Bulk Refund” values (exact names TBD)._
>
>    ⚖️ _**Decision:** We can use the existence of SkuPriceId as the way to identify whether a refund is bulk._
>
> 5. ❌ **Should bulk and single credits be split to clarify when SkuPriceId is required?**
>    This is the same question as for refunds, just about credits for a single SKU vs. bulk credits. Do providers offer credits at a SkuPriceId level? If so, do practitioners need to aggregate all credits together with a single filter? Is “not null” adequate for identifying bulk credits?
>
>    💡 _**Proposal:** Split “Credit” into separate “SKU Credit” and “Bulk Credit” values (exact names TBD)._
>
>    ⚖️ _**Decision:** We can use the existence of SkuPriceId as the way to identify whether a credit is bulk._

#### Commitment utilization

> Scenarios:
> 1. ☑️ **What column do practitioners use to identify used vs. unused commitment discounts?**
>    This is the same as the highest-level breakdown of usage above. Tracking here to also group with commitment utilization issues.
>    - ChargeSubcategory = “Used Commitment” or “Unused Commitment” (as-is)
>    - PricingSubcategory = “Usage Commitment” or “Spend Commitment” or “Unused Commitment”
>    - CommitmentDiscountStatus = “Used” or “Unused”
>
>    💡 _**Proposal:** Move “Used Commitment” and “Unused Commitment” to a dedicated column (name TBD)._
>
>    ⚖️ _**Decision:** Create a new `CommitmentDiscountUsage` column with "Used" and "Unused" values. We will not cover other types of commitments by this column._
>
> 2. ❌ **How do practitioners track used/unused capacity commitments?**
>    The "Unused Commitment" value for ChargeSubcategory was intended to also cover capacity commitments; however, it does not adequately allow you to map the usage to a capacity commitment since there is no column for that and there's no tracking of used capacity commitments. Should we account for this using the same thing for commitment discount utilization? Should this be a separate column? We do not need to solve this for GA, but we should acknowledge it with our decision for 3.
>
>    💡 _**Proposal:** Discuss whether capacity commitments are adequately covered and, if not, if supporting capacity commitments would be a breaking change to decide on next steps._
>
>    ⚖️ _**Decision:** We will revisit this post-GA._

#### Pricing categorization

> Scenarios:
> 1. ❌ **How do we identify "fixed" pricing that does not change over time?**
>    There isn't a way to differentiate between a price that is “fixed” or locked and will not change for some term (e.g., 1 year commitment) from prices that can change every time the “purchase” event happens (e.g., monthly support fees). "On-Demand" is used to indicate a price that can change across billing periods, but does not differentiate between a price that is "fixed" at the time of the initial purchase. There may also be a finer-grained breakdown of fixed pricing, which could include all-upfront, partial upfront, or no upfront purchases.
>
>    💡 _**Proposal:** Add a “Fixed” PricingCategory value for prices that are locked for a publisher-defined term. (Note: The term is not currently represented in FOCUS.)_
>
>    ⚖️ _**Decision:** We will revisit this post-GA._
>
> 2. ❌ **How do we differentiate between fine-grained pricing models?**
>    PricingCategory covers a broad set of pricing models in three high-level buckets for predefined, changing, and discounted pricing. This is too high level and doesn't explain the pricing model in precise enough detail. We need a lower-level breakdown of each PricingCategory value. This was discussed and documented in the PricingCategory supporting content. It was not included in 1.0-preview because of timing. We should include it now. See [example usage scenarios](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/blob/working_draft/supporting_content/columns/pricingcategory.md#example-usage-scenarios) table for proposed PricingSubcategory values.
>
>    💡 _**Proposal:** Add PricingSubcategory as defined in the PricingCategory supporting content._ 
>    See #288
>
>    ⚖️ _**Decision:** We will revisit this post-GA._

### Definition of done

- [x] Rationalize vendor-neutral, cross-cloud naming
- [x] Complete spec template and include naming (code name, display name), constraints, guidelines, compatibility with major providers etc.
- [x] Include principles and governance criteria for maintaining this dimension

** If Normalized Dimension **

Work for generating the normalized list of supported values is tracked in a separate issue. Mappings between normalized values and vendor specified values need to be explored as a part of this work. However, these mappings are not included in the spec documentation. Separate tasks will be created for making these mappings available to practitioners outside of the FOCUS repository.

<br>

## ⭐ Next steps
- [ ] Create a new `CommitmentDiscountUsage` column with “Used” and “Unused” values.
- [ ] Add a new "Credit" value to `ChargeCategory`.
- [ ] Create a new `ChargeClass` column with "Correction" and "Regular" values.
- [ ] Remove `ChargeSubcategory` column.

<br>

### Give it a :+1: below ↴

If you can discuss and help finalize the change, add yourself as an assignee :arrow_upper_right:

Comments are welcome and encouraged!

**Comment by mike-finopsorg** [comment]
Using this doc to build out the examples https://docs.google.com/spreadsheets/d/1tjjfeWCQFyWnE0Mh7nDMK8LV-wKiYracbJrs9QNoLTk/edit#gid=0

**Comment by flanakin** [comment]
In the first discussion, we said that we believe there's a better breakdown of usage charges than its relationship to a commitment discount. The next step was to determine what the name of the column should be where we indicate that a commitment discount was used or not used.

In a subsequent call, there was a question about what a usage breakdown might be, but it didn't seem like there was any real discussion about potential options. I think we need to revisit that and, if we don't have any better breakdown of usage charges, then maybe we just keep what we already had for a usage breakdown. If the relationship to a commitment is actually the best breakdown of usage charges, then there's no need to redefine it.

**Comment by flanakin** [comment]
FYI - Here's the original list of adjustment types that came up in VS2 discussions:

- Refund
  - Usage Correction
  - Price Correction
  - SLA Violation
  - Refund - <refund type>
  - Tax Error
  - Account Closure
- Credit
  - Promo Credit
  - Good Will
- Balance Transfer
- General Adjustment
- Rounding Error

**Comment by hrishikeshsardar** [comment]
This list of adjustments looks good as per our discussion "ChargeCategory Changes" sync-up.

**Comment by thecloudman** [comment]
> FYI - Here's the original list of adjustment types that came up in VS2 discussions:
> 
> * Refund
>   
>   * Usage Correction
>   * Price Correction
>   * SLA Violation
>   * Refund - {refund type}
>   * Tax Error
>   * Account Closure
> * Credit
>   
>   * Promo Credit
>   * Good Will
> * Balance Transfer
> * General Adjustment
> * Rounding Error

This was the first list we created which was voted down. It's a fair bit more information and happy if this list goes up.

**Comment by ijurica** [comment]
**Suggestion regarding Dynamic Pricing Category**

>
>Charges priced at a variable rate determined by the provider. This includes any product or service with a unit price the provider can change without notice, like interruptible or low priority resources.

As discussed at the consistency review meeting, it's recommended not to use spot instances or interruptible instances as examples of dynamic pricing category since some providers offer them at fixed rates for the duration of the billing period.

**A question, unrelated to Pricing category :(**

Although not explicitly specified, if memory serves correctly, spot and/or interruptible instances are expected to have a dedicated SkuId or, at minimum, a dedicated SkuPriceId, similar to BYOL, right?

**Comment by flanakin** [comment]
Status update:
1. Credits will be promoted to `ChargeCategory`.
2. Refunds will be moved to a new `ChargeClass` column to differentiate refunds per ChargeCategory.
3. Commitment status will be moved to a new `CommitmentDiscountUsage` column that will focus solely on traditional usage and spend commitments and not negotiated discounts, capacity commitments, etc.
4. `ChargeSubcategory` will be removed.
   > _NOTE: The group accepted that this means we cannot differentiate between rounding errors and other adjustments in FOCUS columns going forward._

Next steps:
1. Finalize PR #355 for 1-2 above.
2. Create PRs for 3 and 4 (or add to the existing PR).
3. Discuss PricingCategory breakdowns.
4. Discuss single vs. bulk refunds and credits.

Details are available @ https://docs.google.com/spreadsheets/d/1B-MljgsBl2AXdLVqiL-92MoRfjaAHsflCk6oNEaWNQQ/edit?usp=sharing

**Comment by flanakin** [comment]
> if memory serves correctly, spot and/or interruptible instances are expected to have a dedicated SkuId or, at minimum, a dedicated SkuPriceId, similar to BYOL, right?

Yes, although I suppose that depends on how those columns are defined. I would definitely expect to see ID values in both columns.

**Comment by flanakin** [comment]
Given this original conceptual classification of refunds...
* Usage Correction
* Price Correction
* SLA Violation
* Refund - {refund type}
* Tax Error
* Account Closure

Should we consider more values in ChargeClass than just `Correction`? 🤔

- Usage Correction, Price Correction, and Tax Error all fit into "Correction".
- Would practitioners like to see SLA Violation separate from those?
- What other refund types are there?
- How is Account Closure represented? Does it have a ChargeCategory?

**Comment by flanakin** [comment]
Today, we made the following decisions:
1. We will use the existence of SkuPriceId to determine whether a refund or credit is single or bulk.
2. We will not introduce a new "Fixed" pricing category value.
3. We will change the "On-Demand" pricing category to "Standard".
4. We will change the "Commitment-Based" pricing category to "Committed".

**Comment by jpradocueva** [comment]
Reopen as PR #382 and #383 are still open

**Comment by flanakin** [comment]
Today, we decided to push PricingSubcategory to be post-GA.

Please review the following PRs to help close this issue:
- #382 
- #383
