### ISSUE TITLE
Provider's FOCUS schema

### ISSUE THREAD

**Issue by marc-perreaut** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#333]
### Description
> With the introduction of FOCUS essential, some columns become optional. As a practitioner, I would like to know what columns are expected to be present in a FOCUS dataset coming from a provider, so as I can validate and ingest data properly.

### Proposed approach
> Providers could file a schema along with the FOCUS dataset. The approach is similar with the XSD schema used to validate XML files. The schema would contain at least the columns that are present in the dataset, and optionally the possible values of some columns, like the ServiceName.

### Github issue or Reference
> None, to my knowledge.

### Context
> We discussed this in the meeting "FOCUS - Task Force 1 Weekly" on 20FEB.

**Comment by marc-perreaut** [comment]
I believe this issue can be closed, as it is now with the introduction of meta-data.

**Comment by jpradocueva** [comment]
Classified as `Metadata` by the Maintainers on the May 24 call
