### ISSUE TITLE
GroupingAccount{ID,Name} to track sets of SubAccounts

### ISSUE THREAD

**Issue by cnharris10** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#335]
### Type
> Dimension
Normalized? Yes

### Description
> Major clouds support grouping mechanisms for categorizing sets of Accounts AWS), Subscriptions (Azure), and Projects (GCP).  Respectively, these are Organizational Units (AWS), Management Groups (Azure), and Folders (GCP).  Additionally, each grouping mechanism can be nested meaning, for example, that Organizational Units within AWS can contain other Organizational Units and so across clouds.  AWS limits nesting to 5 levels, Azure to 6 levels, and GCP to 10 levels.

### Definition of done

- [ ] Rationalize vendor-neutral, cross-cloud naming
- [ ] Complete spec template and include naming (code name, display name), constraints, guidelines, compatibility with major providers etc.
** If Normalized Dimension **
- [ ] Include principles and governance criteria for maintaining this dimension

** If Normalized Dimension **
Work for generating the normalized list of supported values is tracked in a separate issue. Mappings between normalized values and vendor specified values need to be explored as a part of this work. However, these mappings are not included in the spec documentation. Separate tasks will be created for making these mappings available to practitioners outside of the FOCUS repository.

**Comment by ijurica** [comment]
This issue is closely related to #301.

**Comment by flanakin** [comment]
As much as I prefer explicit columns, I fear we can't guarantee a single parent-child relationship in the future. I could just as easily see a graph of accounts. Admittedly, maybe thinking about this as a grouping of subaccounts might also be limiting. Is it really more about the resource hierarchy? 🤔

**Comment by udam-f2** [comment]
Duplicate. Tracked in #301
