### ISSUE TITLE
[Proposal] Add support for displaying the source and breakdown of one or more discounts on a single line item.

### ISSUE THREAD

**Issue by AWS-ZachErdman** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#338]
### Type
Type of issue: Metric
Normalized? No

### Description
Cloud customers want to use their cost and usage data to verify that their discounts were applied correctly by the cloud provider. This can be challenging to do when multiple discounts apply to a single line item. Today, some cloud providers provide separate columns for each discount that applies to a given line item. With these columns, customers can verify the discounts were applied and easily group them to calculate their sum or distribution.

Currently, the FOCUS spec does not provide any guidance for how cloud providers provide the breakdown of different discounts. AWS believes this is an essential use case the FOCUS team should provide more guidance.We suggest adding a column named “Discounts” to address this use case. A draft proposal of the column is provided below:

### Column Proposal

**Explanation** 
The Discounts column provides the breakdown of all discounts that were applied to a line item to reduce the amount the customer was billed. The Discounts column enables customers to understand which discounts were applied and how each contributed to the difference between ListCost and BilledCost.

The Discounts column has the following requirements:
1.     Discounts MUST contain the complete set of discounts that were applied to a given line item.
2.     The sum of values in the Discount column SHOULD equal the difference between ListCost and BilledCost.
3.     Discounts column MUST be in Key-Value Format.
4.     Each Key MUST be the name of the discount being applied.
5.     Each Value MUST be the Number type and MUST represent cost value of the discount being applied

**Sample data** 
{“discount-name-1”: 0.4, “discount-name-2”: 0.3}

**Description**
The list of all discount values that apply to a given line item. The sum of values in this list equals the difference between the ListCost and the BilledCost. 

**Column Constraints**
Column type : Metric
Column required: FALSE
Allows nulls: TRUE
Data type: JSON
Value format: Key-value

### Definition of done

- [ ] Rationalize vendor-neutral, cross-cloud naming
- [ ] Complete spec template and include naming (code name, display name), constraints, guidelines, compatibility with major providers etc.

**Comment by udam-f2** [comment]
@AWS-ZachErdman 

This is something important and was discussed quite a bit early on. Without most providers supporting discount details in the cost and usage details today, we ended up settling on focusing on commitment discounts first. 

Could you elaborate on the types of discounts that you'd like to see listed here? Are they negotiated-discounts (e.g. EDP, custom pricing etc.) or are you considering tiered pricing as discounts (when moving beyond the base level? or other types?

Also, what does the identifier specified in the 'discount-name' reference? In case of negotiated discounts, some discount provisions may be in a contract.. e.g. Using above 10000 cores gives an additional discount % or something of that sort. Would those have to have a unique name that consumers can reference back?

**Comment by cnharris10** [comment]
Given the current version that I am _not_ arguing is perfect, would this be a viable workaround for now?

Above requirements:
1.     Discounts MUST contain the complete set of discounts that were applied to a given line item. ❓(is a complete set but over N line items)
2.     The sum of values in the Discount column SHOULD equal the difference between ListCost and BilledCost. ✅ 
3.     Discounts column MUST be in Key-Value Format. ✅ (as provider tags)
4.     Each Key MUST be the name of the discount being applied. ✅
5.     Each Value MUST be the Number type and MUST represent cost value of the discount being applied ❓(tags are all strings, so discount total can be derived from `ListCost - BilledCost` per line item)
- 

```
ChargeCategory: Adjustment
ChargeSubCategory: Credit
ResourceID: <some_resource_id>
ListCost: `$0`
BilledCost: `-$0.40`
Tags: { "discounts:name":"1"}
----------------------------------------
ChargeCategory: Adjustment
ChargeSubCategory: Credit
ResourceID: <some_resource_id>
ListCost: `$0`
BilledCost: `$-0.30`
Tags: { "discounts:name":"2"}
```

**Comment by flanakin** [comment]
FYI - This is the same as #310

**Comment by AWS-ZachErdman** [comment]
@udam-f2 I think it would be good to show anything that explained the difference between ListCost vs. BilledCost or EffectiveCost. The first goal would be to show the difference between List and Billed Cost, which would include the negotiated discounts you mentioned (and would probably exclude tiering, depending on whether List price should show the current pricing tier).

A second goal could be to have either the same column or another column also break down the cost between List and Effective cost which could explicitly include the discount from commitment.

The discount name would be to identify the specific discount. Might make more sense to standardize on an ID with some semantic meaning to address where it's not a simple name like the example you gave.

**Comment by AWS-ZachErdman** [comment]
> 5\. Each Value MUST be the Number type and MUST represent cost value of the discount being applied ❓(tags are all strings, so discount total can be derived from `ListCost - BilledCost` per line item)

Sorry I'm not following your comment here Chris. I'm saying Discounts would be a different column than tags. What do you mean here?

**Comment by AWS-ZachErdman** [comment]
> FYI - This is the same as #310

Nice I'm happy to merge these. Is there any Focus group started yet on this issue? Could we consider doing that?

**Comment by udam-f2** [comment]
@AWS-ZachErdman Would be good to know if AWS considers this a blocker / p0. Otherwise, we plan to address #310 as a fast follow. 

There's been talk of an appendix to help explain the different cost metrics for a while. We've not gotten around to it. Also interested in getting a sense of if that would be a p0 or can come soon after.

**Comment by AWS-ZachErdman** [comment]
@udam-f2 I will talk with my team in the next couple days and get back to you on whether its a blocker.

I think explaining the different cost metrics could wait. I'm more interested in getting more clarity on how the different line items should appear (https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/341) as that will help reduce the likelihood any provider has to make breaking changes later to match the spec.

**Comment by AWS-ZachErdman** [comment]
Hi @udam-f2 I'm researching and meeting again about this tomorrow, but we need a way for customers to verify their different discounts in FOCUS. Right now this seems like the best way.

**Comment by AWS-ZachErdman** [comment]
@udam-f2 This one is important for AWS to resolve for 1.0. Many customer inquiries are related to discount validation and we are concerned the spec won't enable customers to trace their discounts enough.

I'm happy to lead a task group on this with others who are interested.

**Comment by udam-f2** [comment]
@AWS-ZachErdman to be clear, you're saying it must be in v1.0 and not a subsequent release like v1.1? if so, yes, we'll need to get the discussion going ASAP (and yes, would love for you to drive it). These never go as fast as we expect :) 

We will schedule this for discussion in the maintainer meeting on Monday.Please address why it needs to be in v1.0 specifically in comments here (there are many other important non-breaking things we're delaying to v1.1 or later so we can get something out there and iterate). Additionally, would be good if you can join Monday's maintainer call at 1 pm PT or have Dennis join to represent the AWS views.

cc @mike-finopsorg

**Comment by jpradocueva** [comment]
@AWS-ZachErdman We need a PR by April 18th. Otherwise, the topic will be moved to v1.1

**Comment by AWS-ZachErdman** [comment]
Hi @jpradocueva understood, thanks. I discussed this with @udam-f2 and we thought it would be okay to move this to v1.1

**Comment by jpradocueva** [comment]
Classified as `Discounts` by Maintainers on May 24 call.

**Comment by AWS-ZachErdman** [comment]
Do we want to add this to 1.1?
