### ISSUE TITLE
[Attribute Suggestion] Default column order in FOCUS

### ISSUE THREAD

**Issue by AWS-ZachErdman** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#340]
### Description
The columns are presented alphabetically in the specification document, but what is the default order of the columns in the schema when appearing to the customer? Should that order change or not change as new columns are added?
 
This will help cloud providers decide the default order for presenting the columns in exports.

### Proposed approach
The FOCUS spec should be explicit that there is no preferred column order specified. It is up to cloud vendors to decide what order they want to provide columns and whether they want to commit to an order with their customers.

### Github issue or Reference
N/A

### Context 
Depending on their level of sophistication, some customers may reference columns by number. The spec should be clear that an order is not guaranteed.

**Comment by udam-f2** [comment]
Assigning for visibility prior to 3/4/2024 maintainer sync

**Comment by flanakin** [comment]
I would love to see us be explicit about this. It came up in Oct/Nov and we removed it from the PR. All we explicitly say is that external (x_) columns must be after the FOCUS columns. I would love to see them be alphabetized. Perhaps we can start with a simple poll to vote for explicitly alphabetized or not to get a gut check from everyone.

For context, I never liked the idea of an alphabetized list until I started using it. It's SOOOOOOOO much easier to use. You ALWAYS know where the columns are. It works especially well for groups of columns that share the same prefix. The ones that don't are more annoying to find (e.g., BilledCost, EffectiveCost, ListCost).

**Comment by AWS-ZachErdman** [comment]
> I would love to see us be explicit about this. It came up in Oct/Nov and we removed it from the PR. All we explicitly say is that external (x_) columns must be after the FOCUS columns. I would love to see them be alphabetized. Perhaps we can start with a simple poll to vote for explicitly alphabetized or not to get a gut check from everyone.
> 
> For context, I never liked the idea of an alphabetized list until I started using it. It's SOOOOOOOO much easier to use. You ALWAYS know where the columns are. It works especially well for groups of columns that share the same prefix. The ones that don't are more annoying to find (e.g., BilledCost, EffectiveCost, ListCost).

@flanakin I 100% agree about alphabetization being so much nicer to use. My only hesitation about dictating an order of columns is that some less advanced users may rely on a certain column order and could be disrupted by us changing the relative order when new columns are added.

It may not be a big deal depending on how a customer receives the data from the cloud vendor though (are they required to select and order the columns they want or is it decided for them by the vendor?)

**Comment by kk09v** [comment]
Here's the current verbiage on this suggesting that the columns MAY be alphabetized and that FOCUS columns SHOULD be segregated and placed before any the custom columns.
https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/blob/working_draft/specification/attributes/column_naming_convention.md#requirements

In our typographic conventions, I'm not seeing a keyword that more explicitly indicates that something is not required without prohibiting it.
https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/blob/working_draft/specification/attributes/column_naming_convention.md#requirements

On a related note, @rileyjenk is working on a requirement that the schema be provided along with the FOCUS data which I think will fit in with this issue and mitigate some of the concerns. E.g. column order would be guaranteed to match the schema, schema would be versioned and updated when additional columns are added

**Comment by jpradocueva** [comment]
@kk09v, Karl, this issue was assigned to you to drive from here to group discussion and final review & approval.

**Comment by ljadvey** [comment]
After much thought from Oct/Nov I agree with alphabetic ordering.

**Comment by jpradocueva** [comment]
@AWS-ZachErdman We need a PR if we want to proceed with this topic.

**Comment by AWS-ZachErdman** [comment]
@kk09v pointed out we already mention alphabetical order which is great.

For this release we could consider changing "MAY be sorted alphabetically" to "SHOULD be sorted alphabetically" since the group seems to agree alphabetical is best.

In a future release, we could consider breaking this section out of column naming more explicitly because I think this line is easily missed.

**Comment by jpradocueva** [comment]
Change attribute name to "Naming and ordering convention". 
Zach will provide a PR link to this issue

**Comment by AWS-ZachErdman** [comment]
PR here: https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/405
