### ISSUE TITLE
[Content Suggestion] Tag key appearance

### ISSUE THREAD

**Issue by AWS-ZachErdman** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#342]
### Description
Should the list of tag keys included in the JSON object be the same list across all line items in a FOCUS export? Even when not all line items have a value for every tag? 
It’s not quite clear, but this particular requirement in "2.37 Tags" 

> "A Tag key without a specified value MUST have its tag value set to null."

seems to indicate that all appearing tag keys should be present in every line item, even when a line item lacks a value for a tag.

### Proposed approach
We should remove this requirement. There isn't a good reason to force a tag key to appear when it is null.

We should also consider adding a requirement

>"A Tag key without a specified value should not appear in the Tag column JSON object for a given line item".

### Github issue or Reference
N/A

### Context
N/A

**Comment by udam-f2** [comment]
That was not the intention. I believe the intention was to cover the scenario where providers only allow a 'label' to be specified but not a key-value pair. 

@cnharris10 could you work with @AWS-ZachErdman to get clarification for this out as a PR, please.

**Comment by cnharris10** [comment]
Yes, the intention here is to effectively capture tags that do not contain a value. In the case where a tag is this single entity, these tags should not be dropped, so guidance is to default their value to null. 

GCP is the prominent example where network tags do not contain a value:
https://cloud.google.com/vpc/docs/add-remove-network-tags

In the case where a tag is a key/value pair, tags keys that are null should be disregarded.

**Comment by AWS-ZachErdman** [comment]
Hi @cnharris10, your comment cleared it up a lot for me, thank you!

I think adding/modifying something like the two lines you said would help a lot.

> In the case where a tag is a single entity and has been assigned to a resource, the tag key should appear in the tags column with the value set to null.
> In the case where a tag is a key/value pair, tag keys for which the value is null SHOULD NOT be included in the tags columns.

The only part I'd want to confirm, is that no cloud provider has key-value tags with "meaningful" null values for a given key where they should be included in the tags column.

**Comment by cnharris10** [comment]
Sounds good, I'll propose an amendment with this and tag you. Thanks for contributing.

**Comment by flanakin** [comment]
Why do we need to declare that tags with a null value should not be in the data? I don't agree with that. I like the first sentence clarifying that label-only tags should have a null value, but the second doesn't seem to be needed since a key-value tag system may also support null values. Microsoft does, for instance. I'm assuming others do as well.

**Comment by AWS-ZachErdman** [comment]
> Why do we need to declare that tags with a null value should not be in the data? I don't agree with that. I like the first sentence clarifying that label-only tags should have a null value, but the second doesn't seem to be needed since a key-value tag system may also support null values. Microsoft does, for instance. I'm assuming others do as well.

That's fair. I just wanted to avoid any language that suggested that the key of key-value tags always had to appear if the value was null (or never specified for that resource).

**Comment by udam-f2** [comment]
That makes sense. FOCUS is not trying to get into how providers design their capabilities. We should where possible keep it to how the data is delivered. In this case, if a provider considers it to not be a valid tag when a value is not specified (it likely never gets created on the resource anyway), they can choose to not provide the k/v pair. If we need to clarify the language to make that clear, we should do that. Should we have language to state that only 'valid' tags based on provider tagging rules should appear in the data? OR is that implied?

**Comment by AWS-ZachErdman** [comment]
That sounds good!

Yeah I think some language clarification could be good. This line was causing us some uncertainty as to what tag keys need to be included for a given resource.
> "A Tag key without a specified value MUST have its tag value set to null."

Without this line I agree it's implied that "only valid tags" should appear for a given line item. Maybe we can instead just clarify this line to indicate it only applies for tags that cannot hold values?
> "A Tag which only consists of a key and cannot hold values MUST have its tag value set to null."

**Comment by silvexis** [comment]
Sorry for the OCD question, but shouldn't it read "does not" vs. "cannot"?

> "A tag that only consists of a key and does not hold values MUST have its tag value set to null."

**Comment by AWS-ZachErdman** [comment]
@silvexis We're actually purposely trying to say that the "key only tags" (e.g., labels) are required to have their values set to null.

If a "key-value tag" does not have a value (e.g., it was never specified for a particular resource), we shouldn't be required to show that tag key with a null value.

**Comment by cnharris10** [comment]
@rileyjenk makes a good point around using true (bool) instead of null as the default value for labels. His reasoning centers around the absence of a value and a null value could be evaluated as equal (Riley, keep me honest)

If we change the default value to true, then we still run into a clobbering issue but it's effectively a nonissue since at least one k/v pair would be provided. 

Thoughts?
@flanakin 
@silvexis 
@AWS-ZachErdman
