### ISSUE TITLE
[Content Suggestion] Effective cost and blending of rates

### ISSUE THREAD

**Issue by AWS-ZachErdman** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#343]
### Description
The definition of EffectiveCost says that it should be inclusive of “all reduced rates and discounts”. This description leaves some ambiguity as to whether it should use the blended rates from pricing tiering that decreases based on usage (e.g., BlendedCost in AWS) or whether it should represent the charge for that specific usage without considering any rate reduction from pricing tiering (e.g. UnblendedCost in AWS).

### Proposed approach 
Most practitioners use and are familiar with rates that do not blend rates of different pricing tiers. EffectiveCost should do the same, but add a line to explicitly acknowledge that it does not include rate blending. Some practitioners may be confused as blending rates could be interpreted as an "Effective Cost".

### Github issue or Reference
N/A

### Context
N/A

**Comment by udam-f2** [comment]
Good call.. Adding a few maintainers to review before the 3/4/2024 maintainer call.

**Comment by flanakin** [comment]
Makes sense

**Comment by AWS-ZachErdman** [comment]
Maybe something like this?

https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/commit/eddbaabde643e324cf0dee9650e1e8c7eba665e9

**Comment by AWS-ZachErdman** [comment]
Created PR here: https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/350

**Comment by AWS-ZachErdman** [comment]
This question about blended costs came up today again at work and I'm interested if the FOCUS community all agrees that blended costs aren't useful for a FinOps practitioner? 

Would a practitioner want to spread the variable rates across all users of a specific service that has different pricing tiers? Or do certain application owners "get lucky" in the sense that their usage of a service might arbitrarily fall into a lower rate tier, while another application owner's usage falls into the higher rate tier?

@mike-finopsorg I know we discussed this briefly on a catch up, would you be able to weigh in on why you don't find blended costs useful?

**Comment by mike-finopsorg** [comment]
The current AWS Blended costs runs into the issues with RI fee handling—specifically they are not included in the blending calculations. From a FinOps perspective blending makes sense if it was applied to the "fully loaded" cost of the resource, however as it stands now in the AWS data it often becomes less useful as EC2 blending is largely impacted when using large amounts of partial/full upfront payments. 

From my experience many practitioners use many different methods to handle cost reporting, but I personally seen the most success with NetSavingsPlanEffectiveCost + OnDemand NetUnblendedCost. In theory, I could have used Blended for non-EC2 services, but that complicates the queries and reporting even further. 

I will add for FOCUS 1.0 nothing is stopping AWS from providing the existing blended rate and blended cost metrics as provider columns.

So my question is if we are to support blending would it be only on the net-effective cost or applied across the metrics we support today (billed, effective, etc)  meaning we have multiple blending columns, with differing complexity to how discount programs are included or excluded.

**Comment by AWS-ZachErdman** [comment]
> The current AWS Blended costs runs into the issues with RI fee handling—specifically they are not included in the blending calculations. From a FinOps perspective blending makes sense if it was applied to the "fully loaded" cost of the resource, however as it stands now in the AWS data it often becomes less useful as EC2 blending is largely impacted when using large amounts of partial/full upfront payments.

Got it, that's helpful!

> From my experience many practitioners use many different methods to handle cost reporting, but I personally seen the most success with NetSavingsPlanEffectiveCost + OnDemand NetUnblendedCost. In theory, I could have used Blended for non-EC2 services, but that complicates the queries and reporting even further.

Does this mean that the scenario of lower pricing tiers getting arbitrarily used for different usage is a reality that some practitioners accept?

> So my question is if we are to support blending would it be only on the net-effective cost or applied across the metrics we support today (billed, effective, etc) meaning we have multiple blending columns, with differing complexity to how discount programs are included or excluded.

I think it makes sense to not include blending in BilledCost since that should represent what you are actually billed for an item. 

The main question for me is: should blending should be included in EffectiveCost? Since it seems many practitioners avoid blended cost, maybe blending should not be included and we should consider a BlendedEffectiveCost column in the future to let practitioners choose between the blended and unblended.

**Comment by mike-finopsorg** [comment]
👍 I would totally be in favour of a future discussion on adding a BlendedEffectiveCost. 

>  Does this mean that the scenario of lower pricing tiers getting arbitrarily used for different usage is a reality that some practitioners accept?

Would love to hear from more of the practitioners in the group on this one.
