### ISSUE TITLE
Attribute: Null handling for columns

### ISSUE THREAD

**Issue by udam-f2** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#35]
Define how null, empty values, n/a and not-set type values should be specified in cost data. Explain which one is the right one to use for different scenarios.

Some scenarios to think about are:
- Nullable columns vs non-nullable columns
- User defined columns such as tags where a user may set an empty string as a valid value
- Is there a scenario where we determine a column as not-nullable but a vendor cannot provide a value?

**Comment by flanakin** [comment]
Thinking about null handling, should we include a placeholder in all column specs for how to identify why a charge has a null value for the specific field? I'm not sure if we can genericize this, but it might be worthwhile walking thru it. We've already identified a number of scenarios where columns are null today. This isn't a 0.5 thing. Just thinking about the issues I've seen when summarizing data based on nullable columns.

**Comment by udam-f2** [comment]
@flanakin Could you please create a discussion topic for this? 
I worry that we're not going to define a complete set of cases where a column may have a null value. However, maybe we can just list a few common scenarios?
