### ISSUE TITLE
FOCUS Metadata Specification

### ISSUE THREAD

**Issue by rileyjenk** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#354]
### Type
MetaData

### Description
> We have multiple use cases that require metadata that ideally are not located within the FOCUS dataset, but rather are information about that dataset that provide information such as what columns are included, recency, and other information. This specification provides a unified format and structure for how FOCUS metadata should be provided. 

### Definition of done

- [ ] Practitioner can easily understand where data is located, how recent it is, what structure of the data is provided
- [ ] Handle API/File based/Database type FOCUS data repository structures
- [ ] Clear structure format for declaring metadata version and contents
- [ ] Organization that handles future metadata groupings

**Comment by udam-f2** [comment]
#340 mentions this WRT to column ordering.

**Comment by ahullah** [comment]
#332 Impacts this in relation to data set versioning

**Comment by udam-f2** [comment]
Is SubAccountType equivalent something to be considered in the metadata v1?

**Comment by mike-finopsorg** [comment]
We should also consider to give some guidance on methods in which metadata can be used to enrich the dataset as it's loaded and document situations in which enriching the FOCUS datasets benefits the user within each metadata item.

**Comment by udam-f2** [comment]
Based on the discussion on 4/2/2024 the following were decided:

- FOCUS should specify what comes via metadata but not how its provided

Schema section:
- Schema is necessary in metadata. Schema should have column_name, provider data type, data encoding, and data length/precision+scale (applicable to string and numeric columns only)

Version section:
- FOCUS compatibility version
- Provider schema version

Generator section:
- Billing data generator to start out in metadata

**Comment by jpradocueva** [comment]
### Summary TF-2 call on Oct 16:
[#298](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/298) and [#534](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/534) Commitment ID and Commitment Discount Columns 
Primary Issue: Ensuring Commitment IDs enable two outcomes for practitioners and that discount unit prices and costs are exposed.
Core Problem: Practitioners needed clearer calculations for Effective Savings Rate (ESR) based on commitment costs, but the current data model lacked support for this.
Divergent Views: Some confusion on whether both issues should be handled together or separately.
Final Agreement: These issues are closely linked and will be handled together under issue #534.
Action Items: 
[TF-2-[#298](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/298), [#534](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/354)] Chris, @cnharris10  is assigned to link the two issues and determine if #534 fully covers #298. He will follow up with relevant contributors and report back.
