### ISSUE TITLE
Billing file generator data needed

### ISSUE THREAD

**Issue by mike-finopsorg** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#357]
### Type
> Type of issue: Dimension
Normalized? No

### Description
> In regards to the InvoiceIssuer it is populated as from the perspective of the billing data generator discussed in more detail in #299 . As data is loaded into a shared data pool it becomes unclear where the source of the data was, it may be clear to the group who downloads and uploads the data into the reporting location, however for the wider group accessing the data it is not clear and having a column that represents this data will resolve this outstanding issue.

### Definition of done

- [ ] Practitioners are able to identify the originating source of the data in order to understand the values used in other fields like InvoiceIssuer

**Comment by udam-f2** [comment]
This can be addressed in section 4. Metadata where we could address how cost data can optionally be enhanced using metadata content for users that prefer to have that in the tabular format instead of separate metadata files.

**Comment by mike-finopsorg** [comment]
Please look to an outcome of #354 before we decide on a column vs metadata.

**Comment by mike-finopsorg** [comment]
Current planning is for this to be part of the metadata in https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/390/files. Once that PR is merged this can be closed out.
