### ISSUE TITLE
Changelog appendix

### ISSUE THREAD

**Issue by flanakin** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#365]
### Type
> Type of issue: Appendix

### Description
> Add a changelog so it's clear what's different between versions. Every PR should update the changelog to ensure it's always up-to-date.

Proposed template per release based on [keepachangelog.com](https://keepachangelog.com):

```markdown
## {version}

**➕ Added:**
- Foo column was added.

**✏️ Changed:**
- Bar attribute requirements were updated with the following:
  - Bar values MUST...
  - Bar values SHOULD...

**🚩 Deprecated:**
- Baz column is now deprecated and will be removed in version 2.0.

**🗑️ Removed:**
- Qux column has been removed.

**🛠️ Fixed:**
- Quux column description was updated to fix a grammatical error.
```

### Definition of done

- [ ] Create a "Changelog" appendix
- [ ] Create a PR template that confirms that people have met all process requirements, like updating the changelog

<br>

### Give it a :+1: below ↴

If you can discuss and help finalize the change, add yourself as an assignee :arrow_upper_right:

Comments are welcome and encouraged!

**Comment by jpradocueva** [comment]
Following the deliberations from the Maintainer's call on April 8th, I propose the creation of a table detailing column names alongside the respective introduction versions. This proposal aims to address the need to indicate to practitioners the deltas between the development revisions:

> Note: this table takes into consideration the changes proposed by PR [#384](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/384/files#diff-1845389740e66ee257bdb7ca08c807f69da829b0037462cafe73c88ffdcf04ae). If this solution is acceptable, we could introduce this table in one of the subsections of the changelog section and remove the `xx.xx Introduced (version)` section from each column.

| **Column Title**                      | **Revision Introduced** |
|-----------------------------------|-------------------|
| Availability Zone                | 0.5               |
| Billed Cost                      | 0.5               |
| Billing Account ID               | 0.5               |
| Billing Account Name             | 0.5               |
| Billing Currency                 | 0.5               |
| Billing Period End               | 0.5               |
| Billing Period Start             | 0.5               |
| Charge Category                  | 0.5               |
| Charge Description               | 1.0-preview               |
| Charge Frequency                 | 1.0-preview              |
| Charge Period End                | 0.5               |
| Charge Period Start              | 0.5               |
| Charge Subcategory               | 1.0-preview              |
| Commitment Discount Category     | 1.0-preview               |
| Commitment Discount ID           | 1.0-preview              |
| Commitment Discount Name         | 1.0-preview               |
| Commitment Discount Type         | 1.0-preview             |
| Contracted Cost                  | 1.0               |
| Contracted Unit Price            | 1.0               |
| Effective Cost                   | 0.5               |
| Invoice Issuer                   | 0.5              |
| List Cost                        | 1.0-preview              |
| List Unit Price                  | 1.0-preview               |
| Pricing Category                 | 1.0-preview               |
| Pricing Quantity                 | 1.0-preview              |
| Pricing Unit                     | 1.0-preview               |
| Provider                         | 0.5               |
| Publisher                        | 0.5               |
| Region ID                        | 1.0               |
| Region Name                      | 1.0               |
| Resource ID                      | 0.5               |
| Resource Name                    | 0.5               |
| Resource Type                    | 1.0-preview              |
| Service Category                 | 0.5               |
| Service Name                     | 0.5               |
| SKU ID                           | 1.0-preview             |
| SKU Price ID                     | 1.0-preview              |
| Sub Account ID                   | 0.5               |
| Sub Account Name                 | 0.5               |
| Tags                             | 1.0-preview               |
| Usage Quantity                   | 1.0-preview             |
| Usage Unit                       | 1.0-preview              |

**Comment by projectlocale** [comment]
No issues here. It's a clear improvement to the state of documentation. Also, Joaquin's suggestion is very practical and probably simplifies things, particularly because we're talking about an appendix.

**Comment by flanakin** [comment]
Reopened the issue since the changelog isn't complete yet.
