### ISSUE TITLE
SkuId, SkuPriceId, and Pricing-related columns review due to ChargeCategory and ChargeClass cleanup

### ISSUE THREAD

**Issue by ahullah** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#366]
### Description
We need to clarify what default values are expected in List, Contracted, Billed & Effective costs in the event that a service provider does not have a publicly published price book

### Proposed approach
This proposal will discuss incorporating appropriate default values in these metrics to ensure data is not 'skewed' when aggregating across multiple providers

### Github issue or Reference
picks up from discussion in PR #331

**Comment by ahullah** [comment]
Including Discussion from PR

[specification/columns/listcost.md](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/331/files#diff-b7c0c9eeddf417d9d4a5f582e25af2646b81defd4dc4be6587bcd6f9be76c827)
@@ -26,7 +26,7 @@ Cost calculated by multiplying List Unit Price and the corresponding Pricing Qua
| Constraint      | Value                   |
|:----------------|:------------------------|
| Column type     | Metric                  |
| Column required | True                    |
| FOCUS Essential | True                    |
Member
@[rileyjenk](https://github.com/rileyjenk) rileyjenk [2 weeks ago](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/331#discussion_r1513230022)
Does this require that the vendor publish a list cost...though that may not actually be published? I see this as a stumbling block for many vendors to adopt even single line item focus data.

Member
@[rileyjenk](https://github.com/rileyjenk) rileyjenk [2 weeks ago](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/331#discussion_r1513235714)
Question answered in discussion today. @ijurica perhaps we ensure it is clear that in the absence of a list price it matches BilledCost.

Member
Author
@[udam-f2](https://github.com/udam-f2) udam-f2 [2 weeks ago](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/331#discussion_r1513254449)
@rileyjenk What's the scenario where a provider doesn't have a list cost? Billed cost is based off of ListCost + discounts. Or are you suggesting that providers may not want to publish the List Cost and also make it available in the billing data to keep that private?

Member
@[flanakin](https://github.com/flanakin) flanakin [last week](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/331#discussion_r1525469358)
Marketplace charges might be a scenario. I don't think those are always published in public price lists. I believe there are more scenarios that aren't in the price list.

Member
Author
@[udam-f2](https://github.com/udam-f2) udam-f2 [3 days ago](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/331#discussion_r1530697586)
We're not specifying that it needs to be 'public' anywhere. Many providers don't publish rates publicly but they will privately tell you the starting point for price/cost (list price/cost) and then go from there to a negotiated price/cost for you.

Member
Author
@[udam-f2](https://github.com/udam-f2) udam-f2 [3 days ago](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/331#discussion_r1530842042)
"The List Unit Price represents the suggested provider-published unit price for a single Pricing Unit of the
associated SKU, exclusive of any discounts."

Member
@[flanakin](https://github.com/flanakin) flanakin [yesterday](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/331#discussion_r1533481251)
I interpreted "provider-published" to mean that I must publicly "publish" prices. If we remove that, the sentence still conveys the same point. Maybe we just simplify?

The List Unit Price represents the suggested unit price for a single Pricing Unit of the
associated SKU, exclusive of any discounts.

Member
Author
@[udam-f2](https://github.com/udam-f2) udam-f2 [yesterday](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/331#discussion_r1534304191)
not against that. In some ways, its not saying suggested by who but maybe that's broadly understood with things like MSRP? @ijurica FYI Thoughts? ^^

Member
Author
@[udam-f2](https://github.com/udam-f2) udam-f2 [yesterday](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/331#discussion_r1534336294)
The List Unit Price represents the Provider suggested unit price for a single Pricing Unit of the
associated SKU, exclusive of any discounts.

How about this?

**Comment by ahullah** [comment]
Discussed on 28.3.24, there is a conflict between  quantity and unit price requirements when sku price id is not present and the need to not introduce artificial variance when the 4 cost columns are not in sync... ie one column contains a value but others are NULL. we will follow up in this  after #364 is merged

**Comment by ijurica** [comment]
Discussed at the TF-1 meeting on 4/16/2024. Decided to create a PR to address the following:

- Review SkuPriceId spec, price, cost, quantity metrics, etc., impacted by the ChargeCategory cleanup.
- Address edge cases related to the correction of quantity with no cost impact and vice versa.

**Comment by ijurica** [comment]
The following table should undergo further review. It will serve as the basis for reviewing the SkuPriceId spec, as well as price, cost, quantity metrics, etc., impacted by the ChargeCategory cleanup

| ChargeCategory | ChargeClass | perSku/bulk                       | SkuId       | SkuPriceId     |
|----------------|-------------|-----------------------------------|-------------|----------------|
| Usage          | Regular     | MUST be perSku and perSkuPrice     | MUST not be null | MUST not be null |
| Usage          | Correction  | MAY be bulk                       | MAY be null | MAY be null    |
| Purchase       | Regular     | MUST be perSku and perSkuPrice     | MUST not be null | MUST not be null |
| Purchase       | Correction  | MAY be bulk                       | MAY be null | MAY be null    |
| Credit         | Regular     | MAY be bulk                       | MAY be null | MAY be null    |
| Credit         | Correction  | MAY be bulk                       | MAY be null | MAY be null    |
| Adjustment     | Regular     | MAY be bulk                       | MAY be null | MAY be null    |
| Adjustment     | Correction  | MAY be bulk                       | MAY be null | MAY be null    |
| Tax            | Regular     | MAY be perSku and MUST NOT be perSkuPrice | MAY be null | MUST be null   |
| Tax            | Correction  | MAY be perSku and MUST NOT be perSkuPrice | MAY be null | MUST be null   |

**Comment by ijurica** [comment]
Considering the initial discussion topic/concern was resolved and new action points were raised  at the TF-1 meeting on 4/16/2024, I've renamed the issue (aligned it with the related PR)
