### ISSUE TITLE
Charge Frequency not in Essentials

### ISSUE THREAD

**Issue by rupagcp** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#371]
I don't think "Charge Frequency" should be marked in FOCUS "Essentials". It is not needed for Invoice Recon (which is the purpose of Essentials). It's more for forecasting use case.

**Comment by jpradocueva** [comment]
@rupagcp This issue will be integrated into a PR after the approval of PR #331.

**Comment by jpradocueva** [comment]
### Current Definition of ChargeFrequency (9ff3ed5)
>Charge Frequency indicates how often a charge will occur. Along with the charge period related columns, the Charge Frequency is commonly used to understand recurrence periods (e.g., monthly, yearly), forecast upcoming charges, and differentiate between one-time and recurring fees for purchases. 
>
>The ChargeFrequency column MUST be present in the billing data and MUST NOT be null. This column is of type String and MUST be one of the allowed values. When ChargeCategory is "Purchase", ChargeFrequency MUST NOT be "Usage-Based. 

The following options are proposed to replace the above statement:

### Option A for ChargeFrequency (With Restriction Applied):
**IF** the billing data is reported for forecasting *'ChargeFrequency'* column *SHOULD* be present in the billing dataset, and the field *MUST* be a non-empty string and adhere to one of the defined values:
* 'One-Time': For charges occurring just once.
*'Recurring': For regularly scheduled charges.
* 'Usage-Based': For charges based on service usage.
    * *IF* *'ChargeCategory'* column equals 'Purchase,' *'ChargeFrequency'* **SHOULD NOT** be 'Usage-Based.' 

**IF** the billing data is reported for reconciliation purposes, the *'ChargeFrequency'* column *MAY* be excluded from the billing dataset.

### Option B for ChargeFrequency (With Restriction Applied):
**FOR** forecasting purposes, the *ChargeFrequency* column **SHOULD** be present in the billing dataset, and its value **MUST** be a non-empty string that accurately reflects the charge type according to the following values:
* 'One-Time': For charges occurring just once.
* 'Recurring': For regularly scheduled charges.
* 'Usage-Based': For charges based on service usage.
     * IF 'ChargeCategory' column equals 'Purchase,' 'ChargeFrequency' SHOULD NOT be 'Usage-Based.' 
* ‘Not-Applicable’: e.g. for reconciliation purposes

**FOR** reconciliation purposes, the *‘ChargeFrequency’* column **MAY** set to ‘Not-Applicable.’ 

### Option C for ChargeFrequency (With Restriction Applied):
The ‘ChargeFrequency’ column MUST be present in the billing dataset, and its value MUST be a non-empty string that accurately reflects the charge type according to the following values:
* 'One-Time': For charges occurring just once.
* 'Recurring': For regularly scheduled charges.
* 'Usage-Based': For charges based on service usage.
* IF 'ChargeCategory' column equals 'Purchase,' 'ChargeFrequency' SHOULD NOT be 'Usage-Based.' 
* ‘Not-Applicable’: e.g., for reconciliation purposes

**Comment by rupagcp** [comment]
Thanks for sharing Joaquin. Of the options I do think Option A makes most sense bc it's saying ChargeFrequency can be excluded for reconciliation.  Applicable vs. not applicable (option B) opens a can of worms that feels 1.1+

**Comment by jpradocueva** [comment]
During the maintainer's meeting, the idea of conducting a poll to determine the required level for the ChargeFrequency column was put forward. After deliberations, we have outlined three options to enhance the current definition of the ChargeFrequency column. Your feedback will assist us in choosing the most effective and advantageous approach. Kindly indicate your preference by adding a `:+1` next to the option that aligns best with your requirements.

**Comment by jpradocueva** [comment]
During the maintainer's meeting (April 8th), a poll was proposed to determine the required level for the **ChargeFrequency** column. After some deliberations, we have outlined three options to enhance the current definition of the **ChargeFrequency** column. Your valuable feedback will assist us in choosing the most effective and advantageous approach. Kindly indicate your preference by upvoting the option that aligns best with your requirements.

**Comment by jpradocueva** [comment]
### Option B for ChargeFrequency (With Restriction Applied):
**FOR** forecasting purposes, the *ChargeFrequency* column **SHOULD** be present in the billing dataset, and its value **MUST** be a non-empty string that accurately reflects the charge type according to the following values:
* 'One-Time': For charges occurring just once.
* 'Recurring': For regularly scheduled charges.
* 'Usage-Based': For charges based on service usage.
        * IF *'ChargeCategory*column equals 'Purchase,' *'ChargeFrequency'* **SHOULD NOT** be 'Usage-Based.' 

**FOR** reconciliation purposes, the *‘ChargeFrequency’* column **MAY** set to ‘Not-Applicable.’

**Comment by jpradocueva** [comment]
### Option C (Optional)
The ChargeFrequency column MAY be present in the billing data, and if present, it MUST NOT be null. This column is of type String and MUST be one of the allowed values. When ChargeCategory is "Purchase", ChargeFrequency MUST NOT be "Usage-Based.

**Comment by jpradocueva** [comment]
### Option D (Optional)
The ChargeFrequency column SHOULD be present in the billing data, and if present, it MUST NOT be null. This column is of type String and MUST be one of the allowed values. When ChargeCategory is "Purchase", ChargeFrequency MUST NOT be "Usage-Based.

**Comment by udam-f2** [comment]
This column is not nullable and normalized. How does a consumer of the data build a FOCUS-compliant dataset to use across the different providers they use when a non-nullable column is not provided?

**Comment by jpradocueva** [comment]
### Option E (Recommended)
The ChargeFrequency column RECOMMENDED be present in the billing data, and if present, it MUST NOT be null. This column is of type String and MUST be one of the allowed values. When ChargeCategory is "Purchase", ChargeFrequency MUST NOT be "Usage-Based.

*Feature Level: RECOMMENDED*

**Comment by jpradocueva** [comment]
TF-2 agreed to create a PR based on option E.
