### ISSUE TITLE
String type attribute: character set and max length

### ISSUE THREAD

**Issue by marc-perreaut** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#373]
### Description
> While discussing about column meta-data in Task Force 1 meeting on 26MAR2024, it was pointed out that it's important for practitioners to know the max size of column values from a provider for data ingestion and storing into data warehouse. In particular, the max size cannot be inferred from the ingested dataset, because the observed max size may vary from one dataset to another.
Thinking further on this, the max size of a column value of string type, as well as the character set, could be specified in FOCUS to apply for all providers, while providers could have the possibility to specify a smaller size and subset of the character set for their columns in their meta-data.

### Proposed approach
> Add a string type attribute, which would specify:
- The character set used for the string type, probably UTF-8, or maybe Unicode, leaving the possibility to use either UTF-8, ITF-16 or UTF32?
Actually, the full FOCUS dataset could be specified to use UTF-8 or Unicode.
- The max size, for example 64 or 128 bytes.
The providers could specify in meta-data a smaller character subset for their columns, eg ASCII, and smaller size, eg 32.

### Github issue or Reference
> There is no related Github issue to my knowledge. The character set can be considered as a specification-wide topic.

### Context
> The context is essentially about data ingestion and storing of FOCUS datasets, in particular column values with string type: practitioners need to know the used character set and max size.

**Comment by jpradocueva** [comment]
It should be specified in the metadata.

**Comment by jpradocueva** [comment]
This issue is linked to PRs #360 and #390. Please provide the comment directly in the PRs.
