### ISSUE TITLE
Within a billing month dataset partition, explicitly state all included columns/properties must be present in all rows. 

### ISSUE THREAD

**Issue by cnharris10** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#374]
### Type
Documentation
Normalized? Yes

### Description
The spec is lacking clarification that no matter the dataset format utilized by a provider (i.e. CSV, Parquet, JSON, AVRO, etc.), any time a column is included at least once as part of the dataset, that same column MUST be included for all rows/objects with a valid value or NULL.

This does _not_ mean that all FOCUS columns must be present in all datasets but that an included column/property must exist across all rows/objects, regardless of the value provided.

This prevents someone looking at a dataset and having to discover which properties exist or don't exist at the row-level.

For columnar formats like CSV and Parquet, this is not an issue.  A column either exists for all rows or no rows.

For object formats like JSON, this can be an issue.  A property can exist within the first object and be absent within the second object.

For example, in the case that a resource's usage charge has an AZ, but it's tax charge does not.  The first example _should_ be deemed invalid and the second example _should_ be deemed correct.

Wrong (the "AvailabilityZone" property is missing completely from the second object but exists in the first.)
```
[
    { "ChargeCategory": "Usage", "ResourceId": "<id>", "AvailabilityZone": "us-east-1a", ... },
    { "ChargeCategory": "Tax", "ResourceId": "<id>", ... },
    ...
]
```

Correct (the "AvailabilityZone" property is included in both objects, regardless of its null or non-null value.)
```
[
    { "ChargeCategory": "Usage", "ResourceId": "<id>", "AvailabilityZone": "us-east-1a", ... },
    { "ChargeCategory": "Tax", "ResourceId": "<id>", "AvailabilityZone": null, ... },
    ...
]
```

**Comment by jpradocueva** [comment]
Classified as `Metadata` by the Maintainers on the May 24 call

**Comment by jpradocueva** [comment]
Classified as `Overall Spec` by the Maintainers on the May 24 call

**Comment by udam-f2** [comment]
Assigning to TF1 for initial discussion (to make sure we have items in the queue - currently only one item assigned)

**Comment by jpradocueva** [comment]
TF-1 agreed to close down this issue on the May 4 call.
