### ISSUE TITLE
Column: AvailabilityZone - Options for CONDITIONAL Expressions

### ISSUE THREAD

**Issue by jpradocueva** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#387]
### Current Definition of AvailabilityZone (9ff3ed5)

'An Availability Zone is a provider-assigned identifier for a physically separated and isolated area within a Region that provides high availability and fault tolerance. Availability Zone is commonly used for scenarios like analyzing cross-zone data transfer usage and the corresponding cost based on where resources are deployed. '

>The AvailabilityZone column SHOULD be present in the billing data when the provider supports deploying resources or services within an Availability Zone. This column MUST be of type String and MAY contain null values when a charge is not specific to an availability zone. 

The following statements provide suggestions on how to this technical requirement could be revised:

### Option A for AvailabilityZone
An Availability Zone is a provider-assigned identifier for a physically separated and isolated area within a Region that provides high availability and fault tolerance. Availability Zone is commonly used for scenarios like analyzing cross-zone data transfer usage and the corresponding cost based on where resources are deployed. 

1.	The 'AvailabilityZone' column SHOULD be present in the billing dataset if the provider enables resource or service deployment within an Availability Zone. 
2.	The 'AvailabilityZone' column MUST be a String type to standardize data entry, facilitating data management and analytics processes.
3.	The 'AvailabilityZone' column MAY contain null values when a charge is not relevant to a specific Availability Zone.
4.     The 'AvailabilityZone' column MAY NOT be present in the billing dataset if the provider does not support provisioning resources into Availability Zones. However, if it is provided, it MUST be null.

### Option B for AvailabilityZone
An Availability Zone is a provider-assigned identifier for a physically separated and isolated area within a Region that provides high availability and fault tolerance. Availability Zone is commonly used for scenarios like analyzing cross-zone data transfer usage and the corresponding cost based on where resources are deployed. 

1.	IF the provider offers the ability to deploy resources or services within an Availability Zone:
•	The 'AvailabilityZone' column SHOULD be included in the billing dataset to reflect this capability.
•	This column MUST strictly be of the String data type.
•	The column MAY have null entries for charges that do not pertain to a specific Availability Zone.

2.	IF the provider does NOT support deploying resources within an Availability Zone:
•	The billing data MUST clearly reflect the absence of this feature. The 'AvailabilityZone' column SHOULD be omitted to avoid misinterpretation.
•	In cases where the 'AvailabilityZone' column is present for standardization across multiple providers, it MUST be consistently populated with a standardized value, such as 'N/A,' to denote non-applicability.

Providers are advised to implement procedures that ensure the 'AvailabilityZone' data is accurate and consistent, thereby aiding customers in effectively managing and scrutinizing their costs in relation to Availability Zones."

**Comment by mike-finopsorg** [comment]
Suggestion for Option A

`For providers that do not support provisioning resources into Availability Zones this column MAY be omitted, however if it is provided it MUST be null.`
