### ISSUE TITLE
Column: CONDITIONAL Statement Alternative

### ISSUE THREAD

**Issue by jpradocueva** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#388]
### Current Definition of Commitment Discount Category (9ff3ed5)
The CommitmentDiscountCategory column SHOULD be present in the billing data when the provider supports commitment-based discounts. This column MUST be of type String, MUST be null when CommitmentDiscountId is null, and MUST NOT be null when CommitmentDiscountId is not null. The CommitmentDiscountCategory MUST be one of the allowed values.

### Option A for reporting Commitment Discount Category 
IF a provider reports commitment-based discounts, THEN the 'CommitmentDiscountCategory' column SHOULD be included in the billing data and:

* The 'CommitmentDiscountCategory' column MUST be of the String data type and MUST contain one of the allowed enumerated values unless specified otherwise:

     * “Spend”: Commitment-based discounts that require a predetermined amount of spend.
     * “Usage”: Commitment-based discounts that require a predetermined amount of usage. 
     *  Additional categories may be included as specified by future updates to this standard."
* Additionally:
    * IF 'CommitmentDiscountId' is null, 'CommitmentDiscountCategory' MUST also be null.
    * IF 'CommitmentDiscountId' is not null, THEN 'CommitmentDiscountCategory' MUST NOT be null and adhere to the allowed enumerated values.

Once the group agrees with the structure of the conditional statement, I will create one PR for each conditional statement in the working-draft.

**Comment by jpradocueva** [comment]
### Option B for reporting Commitment Discount Category

IF a provider supports commitment-based discounts, THEN the 'CommitmentDiscountCategory' column SHOULD be included in the billing data and:

   * The CommitmentDiscountCategory column MUST be of the String data type and MUST contain one of the allowed enumerated values.
   * Additionally:
        * IF CommitmentDiscountId is null, CommitmentDiscountCategory MUST also be null.
        * IF CommitmentDiscountId'is not null, THEN CommitmentDiscountCategory MUST NOT be null and adhere to the allowed enumerated values.

**Comment by ijurica** [comment]
Consider using **"...MUST be present/included... + condition..."** instead of **"... SHOULD be present/included... + condition..."** for Conditional columns.

_Note: Not applicable to AvailabilityZone and ChargeFrequency (Feature level: Optional)_

**Comment by jpradocueva** [comment]
Task Force 2 agreed that the rest of the Conditional columns should be expressed with MUST + Condition. In this case, a new option was suggested:

### Option C for Reporting Commitment Discount Category

The CommitmentDiscountCategory column MUST be present in the billing data when the provider supports commitment-based discounts. The CommitmentDiscountCategory column MUST be of the String data type and MUST contain one of the allowed enumerated values:
* “Spend”: Commitment-based discounts that require a predetermined amount of spend.
* “Usage”: Commitment-based discounts that require a predetermined amount of usage.

Additionally:
* IF CommitmentDiscountId is null, CommitmentDiscountCategory MUST also be null.
* IF CommitmentDiscountId'is not null, THEN CommitmentDiscountCategory MUST NOT be null and adhere to the allowed enumerated values.
