### ISSUE TITLE
Add support for sub categorizations of ServiceCategory

### ISSUE THREAD

**Issue by udam-f2** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#404]
### Type
> Dimension
Normalized? Yes

### Description
> Today, ServiceCategory is defined as the highest-level categorization based on the primary function of the service. However, many find that the highest level of categorization can be too high-level and needs the next-level breakdown. A good example would be the Database ServiceCategory - which naturally has many well-known sub-categories such as Data Warehouses, Relational DB, and No-SQL (not an exhaustive list). 

The request here is to add the subcategorization for ServiceCategory as a fast-follow for v1.0. 

related issue from AWS-ZachErdman: https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/379

**Comment by thecloudman** [comment]
I've been reviewing this in my data and the need for sub categorisation is very much needed but we need to consider other columns in this decision so as not to duplicate data.

In Azure billing data we have meter category, meter subcategory and meter name, these are extremely useful in viewing usage across your azure spend. With FOCUS, these roll up, we have service category, service name and resource type, which means we lose a lot of good data we previously had.

**Azure example in FOCUS format**
![image](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/assets/28718362/4f00bf54-b853-4602-9027-ca2c614f6137)

**Azure example in original format**
![image](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/assets/28718362/d80eebaf-bfbc-49f8-a360-cac0fde4bff3)

The original format is far cleaner and easier to view and use. In FOCUS format we lose some of the detail behind the meters.

My view is we add additional columns which could be:

- _**SKU Description**_ - can replicate meter name column from original data, as each meter has a unique SkuID.
- **_Resource Sub Type_** - which can be the same function as the Meter Category column in the original data. 

I know this only focuses on Azure, but I believe it is fairly straight forwards to map google and AWS to this format.

**Comment by jpradocueva** [comment]
Classified as `Service Category` by the Maintainers on the May 24 call

**Comment by jpradocueva** [comment]
TF1-[#404](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/404): Eric and Tim will work on defining and documenting the rules and principles for subcategorization, ensuring they align with the existing top-level categories.

**Comment by jpradocueva** [comment]
### Action Items agreed during TF-1 on Jul 9 call:

- [ ] TF1-[#404](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/404) Sean: Prepare and present a draft of subcategories.
- [ ] TF1-[#404](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/404) Tim: Coordinate with Shawn for feedback on the draft.
- [ ] TF1-[#404](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/404) All Members: Review the draft when presented and provide feedback
