### ISSUE TITLE
UsageQuantity/Unit should be required based on PricingQuantity differentiation

### ISSUE THREAD

**Issue by flanakin** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#409]
### Type
> Dimension: UsageQuantity

### Description
> The UsageQuantity column requirements say it is only required if the provider supports the "measurement of usage":
>
> > _UsageQuantity column MUST be present in the billing data when the provider supports the measurement of usage._
>
> This means someone could technically have variable, usage-based charges without actually conveying how much was used. This feels wrong. I believe we should change this to be dependent on differentiation from PricingQuantity and PricingUnit. Maybe something like:
>
> > UsageQuantity column MUST be present in the billing data when the provider **supports charges where UsageQuantity may not match the PricingQuantity**.
>
> UsageUnit has the same condition. That should be updated to be based on UsageQuantity to be more clear:
>
> > UsageUnit column MUST be present in the billing data when **UsageQuantity is present**.

### Definition of done

- [x] Complete spec template and include naming (code name, display name), constraints, guidelines, compatibility with major providers etc.

**Comment by jpradocueva** [comment]
The group suggested adding examples for both options.

**Comment by jpradocueva** [comment]
The group had a lengthy discussion and, at the end, decided:
To create two PRs:
* One which explicitly locks UsageQ to usage lines, and
* The other which just keeps it open to purchase lines but updates some language to avoid “measurement of usage”.
