### ISSUE TITLE
Need to review and decide on a Metadata versioning / ID approach

### ISSUE THREAD

**Issue by mike-finopsorg** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#411]
### Type
> Type of issue (e.g. Dimension, Metric, Attribute, Documentation etc.)
Metadata

### Description
> The new metadata section has a DataGeneratorVersion, but there is some disagreement to how this works with the data generator and how schema updates work without an ID. This issue is to track the conversation that will continue after the metadata section is added to the specification. 

### Definition of done

- [ ] Clear plan for metadata versioning/Ids
- [ ] Updated sections of metadata to clearly reflect the outcome of discussions

**Comment by mike-finopsorg** [comment]
During last weeks Weekly Meeting it appeared that there are two ways to think about the metadata entity. 

1) A complete single object that can be versioned. 
        In this model the Data Generator and Schema sections are only provided as a single complete set. 
        Any changes in either section updates the overall version of the metadata
        This model works ok with a single version object e.g DataGeneratorVersion
        Having one version means one relationship to track between Metadata and FOCUS Dataset

2) Multiple Objects each with their own versions/Ids.
        Each section of metadata (currently Data Generator and Schema) is it own entity
        Updates to the Schema section does not cause a version update in the Data Generator section
        This model requires an Id or Version for each section as updates in a section will need to be recorded
        As each section has its own Id/Version a relationship per section of metadata will need to be tracked
        

The way I understand it we have two main paths forward:

1) Stick with a single DataGeneratorVersion and treat metadata as a single wholistic entity.
2) Add a Version/Id back into Schema and allow each section to have its own tracked changes

I have another proposal which at this point is my preferred idea:

* The DataGenerator section should have a principle that only non-changing items are to go into this section, at this point it will be only the name of the DataGenerator
* The DataGeneratorVersion gets removed
* We move TagPrefix from the DataGenerator section into the Schema section with a normative text that says this TagPrefix list MUST be provided for the `Tags` column
* Based on the previous item we establish a design that pushes for column specific elements to be added to Schema definitions
* We add back the SchemaId in the Schema Section and track this (single) Id as the relationship with FOCUS datasets

**Comment by rileyjenk** [comment]
@jpradocueva with the #415 PR this is resolved.
