### ISSUE TITLE
Consistency Review: Review List/Contracted Cost behavior compared to Billed/Effective to ensure no metrics are double counting cost

### ISSUE THREAD

**Issue by udam-f2** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#424]
### Description
List/contracted cost were designed such that they can be compared at a line item level or aggregated level with Billed and Effective for various scopes to quantify savings

It feels like we'd cause double counting of cost into List and Contracted in the case of burn-down scenarios such as RIs.

I assume we model burn-down records (say for RI usage) with:
- ListCost would be the original cost of the instance usage without any discounts
- The ContractedCost would be the ListCost of the same usage with any negotiated discounts applied
- BilledCost would be 0 (assuming all up-front paid)
- EffectiveCost would be just the burn-down portion

I assume the purchase record would have the following semantics:
- ListCost of the RI as advertised
- ContractedCost would be the ListCost negotiated with discounts applied
- BilledCost would be the same as ContractedCost
- EffectiveCost would be 0

This made sense to me till now. Now that I’m looking at the spreadsheet [here](https://docs.google.com/spreadsheets/d/1zA0brhrEntfWlzt5VNcNLBFnKPEiarajTF84o4ATeEw/edit#gid=2135239752) it feels like we’d end up double counting the ListCost and ContractedCost where as BilledCost and EffectiveCost would only be counted once.

The result would then artificially inflate the ListCost - if someone compared List with Billed or sum of effective, they would get tricked into thinking they gained much larger savings than they did. Else they would have to exclude the up-front payments for list cost for RIs

### Proposed approach
> It feels like we should at the minimum make a statement in List/Contracted that if aggregating, ListCost of burn-down purchases (or usage?) will need to be excluded? Usage and Purchases both having a ListCost has value from a reporting perspective when not mixing the two.

### Github issue or Reference
> 

### Context
>

**Comment by udam-f2** [comment]
Closing in favor of the broader consistency review issue: #425

**Comment by AWS-ZachErdman** [comment]
I support the proposed approach. Better to keep ListCost to allow for discount validation for List/Billed/Effective Costs for each line item and note to users that you cannot aggregate on ListCost without removing commitment line items to avoid double counting.
