### ISSUE TITLE
Need a prescriptive way to avoid double-counting List/ContractedCost

### ISSUE THREAD

**Issue by flanakin** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#436]
### Description

> For scenarios where a purchase is for credits or discounts that are then applied to future charges (e.g., commitment discount usage) where both have a ListCost and ContractedCost but one is billed and the other is not (e.g., amortized rows), calculating the sum of either column will result in double-counting for those records. Currently there is no prescriptive way for a practitioner to know how to identify when a record should be excluded from this calculation.

### Proposed approach

> Given the extreme likelihood that nearly every practitioner will get caught by this, we should either:
> 
> 1. Provide a prescriptive way to filter out impacted purchases that works across providers.
> 2. Leave ListCost and ContractedCost null for these rows.
> 3. Poll practitioners to confirm that they find it adequate to double-report the costs and not have a prescriptive, well-defined, provider-agnostic way to resolve the issue.

### Context

To help visualize the issue, let's say:
1. Compute costs $2/day at list
   > $2/day * 365 days = $730/year
3. The org has a 10% negotiated discount
   > $2/day * 0.9 = $1.80/day or $657/year
4. A 1-year commitment is 50% off of list
   > $730/year * 0.5 = $365/year or $1/day amortized
5. The org also has a 20% negotiated discount for compute commitments applied on top of the commitment list cost
   > $365/year (see 4) * 0.8 = $292/year or $0.80/day amortized

| Date | ChargeDescription | ChargeCategory | ListCost | ContractedCost | BilledCost | EffectiveCost |
|---|---|---|---:|---:|---:|---:|
| Jan 1 | Usage Commitment Purchase | Purchase | $365.00 | $292.00 | $292.00 | $0.00 |
| Jan 1 | Committed Compute Hours | Usage | $2.00 | $1.80 | $0.00 | $0.90 |
| Jan 2 | Committed Compute Hours | Usage | $2.00 | $1.80 | $0.00 | $0.90 |
| ... | Committed Compute Hours | Usage | $2.00 | $1.80 | $0.00 | $0.90 |
| Dec 30 | Committed Compute Hours | Usage | $2.00 | $1.80 | $0.00 | $0.90 |
| Dec 31 | Committed Compute Hours | Usage | $2.00 | $1.80 | $0.00 | $0.90 |
||||———|———|———|———|
||| **Sum** | $1095.00 | $949.00 | $292.00 | $292.00 |
||||———|———|———|———|
||| **Actual** | $730.00 | $657.00 | $292.00 | $292.00 |

See #424 for additional details from the original issue.

**Comment by udam-f2** [comment]
I support identifying the problematic columns that could be double counted based on BilledCost > $0 AND EffectiveCost = $0 to identify the charges that can be double counted. While it's not easily identifiable, it gives us a path forward on v1.0 and post v1.0 we could introduce a new column to identify these easily. 

I think zero'ing out billed/contracted for some rows is problematic because many purchases may not fit the burndown scenario and it just complicates row-level analysis and the description of the column (List = published price. These purchases have a published price).
