### ISSUE TITLE
Provide example of difference between Charge and Billing Period

### ISSUE THREAD

**Issue by dinoboy197** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#475]
### Description
It is unclear to me what the difference is between a Charge and a Billing Period are. I see that the description for each is different, but unfortunately those did not help to build my intuition.

### Proposed approach
Would the authors consider a motiviting example in the specification to clarify the difference? For example, a concrete, real-world example where the start and end Billing and Charge dates for a particular entry are different, and why a business might choose to do this?

Thank you so much for your consideration! I'm looking forward to using this specification in my work, but just need a little help on this part :)

**Comment by jpradocueva** [comment]
### Action Item
Maintainers-TF3-[#475](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/475): Irena to prepare and provide sample data.

**Comment by ijurica** [comment]
Hi!

Attaching a few definitions from the specification relevant to this discussion:

>**Billing Period:** The time window that an organization receives an invoice for, inclusive of the start date and exclusive of the end date. It is independent of the time of usage and consumption of resources and services.
 ...
 **Charge Period:** The time window for which a charge is effective, inclusive of the start date and exclusive of the end date. The charge period for continuous usage should match the time granularity of the dataset (e.g., 1 hour for hourly, 1 day for daily). The charge period for a non-usage charge with time boundaries should match the duration of eligibility.
 ...
 **Charge Class:** Charge Class indicates whether the row represents a correction to one or more charges invoiced in a previous billing period.

A couple of assumptions:

- The provider supports a monthly billing period, starting on the 1st of the month.
- The time granularity of the data set is hourly.

A couple of hypothetical charge records (and a subset of relevant columns) that might have been delivered on June 28th:

- Usage incurred on June 26th at 04:00 am
   - ChargeCategory: Usage
   - ChargeClass: null
   - BillingPeriodStart: 2024-06-01T00:00:00Z
   - BillingPeriodEnd: 2024-07-01T00:00:00Z
   - ChargePeriodStart: 2024-06-26T04:00:00Z
   - ChargePeriodEnd: 2024-06-26T05:00:00Z

- Full upfront purchase of an RI (1 year) made on June 26th at 04:00 am
   - ChargeCategory: Purchase
   - ChargeClass: null
   - BillingPeriodStart: 2024-06-01T00:00:00Z
   - BillingPeriodEnd: 2024-07-01T00:00:00Z
   - ChargePeriodStart: 2024-06-26T04:00:00Z
   - ChargePeriodEnd: 2025-06-26T04:00:00Z

- Correction charge record related to usage incurred on May 26th at 04:00 am (note that on June 26th the previous billing period is already invoiced):
   - ChargeCategory: Usage
   - ChargeClass: Correction
   - BillingPeriodStart: 2024-06-01T00:00:00Z
   - BillingPeriodEnd: 2024-07-01T00:00:00Z
   - ChargePeriodStart: 2024-05-26T04:00:00Z
   - ChargePeriodEnd: 2024-05-26T05:00:00Z

I hope those use cases and associated charge records will help clarify the difference between the charge period and the billing period, as well as what information is/should be provided in the corresponding columns.

Feel free to let us know if more clarification is needed

**Comment by ijurica** [comment]
Dear Taylor,
Please let me know if you have any more questions or concerns regarding this topic, or if we can go ahead and close the issue.
Thanks!

**Comment by shawnalpay** [comment]
Discussed in Oct 15 TF1 call and agreed to close.  @dinoboy197, please reopen if you feel this has not been sufficiently addressed.

**Comment by jpradocueva** [comment]
### TF-2 call on Oct 15:
Topic: [#475](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/475) Provide examples of charge and billing period
Discussion Summary: This issue requested clarity on the difference between a charge period and a billing period. Feedback was provided some time ago, and no further clarification requests had been made.
Resolution: The group decided to close the issue but left the option for the author to reopen it if necessary.
