### ISSUE TITLE
FOCUS ISV Onboarding 

### ISSUE THREAD

**Issue by gdj0nes** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#482]
### Description

Are there resources on how as an ISV we can develop a data model that conforms to the FOCUS Spec? I'm on the product team at Pinecone a cloud infrastructure company. We don't yet expose exports and we would like to align with providing exports to at least some of users in the format. While I've read through the spec I find it hard to translate it to our use case.

**Comment by jpradocueva** [comment]
@gdj0nes the group reviewed this issue. See [Maintainers Meetingn Minutes, Jun 17](https://docs.google.com/document/d/1PZeBnY6RmkzcxqYulCEb02fCw7x9QEOKfhuSk66SIyA/edit#heading=h.t460y3nhaau4) for details. Could you please provide further details on the topic? Thanks

**Comment by gdj0nes** [comment]
@jpradocueva I'll take a look once i get access to the document

**Comment by shawnalpay** [comment]
@gdj0nes You should have access to that document as part of your participation in FOCUS.  In any case, that agenda doc just outlines how we discussed the issue you raised, and we were looking for more info.  Could you provide a couple examples of questions you have and/or where the spec doesn't meet your needs?  Or even just some general questions you might have would be helpful.

**Comment by shawnalpay** [comment]
Discussed in Oct 15 TF1 call and agreed to close.  @gdj0nes, please reopen and provide further context if you see fit!

**Comment by jpradocueva** [comment]
### TF-2 call Oct 15:
Topic: [#482](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/482) ISV onboarding
Discussion Summary: The issue, raised in June, related to resources available for ISVs to develop models conforming to the focus spec. There was a lack of clarity on what specific resources were needed.
Resolution: As no further clarification was provided by the original author, the team agreed to close the issue with the option to reopen it if needed.
