### ISSUE TITLE
ChargeClass value in case of late arriving charge records

### ISSUE THREAD

**Issue by ijurica** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#491]
### Type
> Dimension
Normalized? Yes

### Description
Current description of Charge Class:
> Indicates whether the row represents a correction to one or more charges invoiced in a previous billing period. 

The definition should also encompass late-arriving charge records, e.g., a usage-related record that occurred in a previously invoiced billing period. In such cases, there is no original charge, only this late-arriving one, which should also be classified as 'Correction' or we might decide to introduce an additional value.

**Comment by jpradocueva** [comment]
### Pending Action Items:
- [ ] TF1-[#491](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/491) Irena will prepare a PR.

**Comment by ijurica** [comment]
Current version

> Charge Class indicates whether the row represents a correction to one or more charges invoiced in a previous billing period.

Suggested change:

> Charge Class indicates whether the row represents a correction to a previously invoiced billing period.

In case of late arriving costs, there might not be previous charges that we are explicitly correcting, but rather correcting the invoiced billing period as a whole. I believe this should be classified as 'Correction', but if needed, we can consider adding an additional value.

_Note to self: don't forget to address the Description as well._
