### ISSUE TITLE
[ADMIN] FOCUS Roles & Tasks

### ISSUE THREAD

**Issue by jpradocueva** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#493]
### Description
The FOCUS project is structured around a framework of roles critical to its operational excellence and strategic direction, including Working Group Members Chair, Task Force Conveners, Maintainers, Editors, Members, and the Program Manager. Each role contributes uniquely, ranging from overseeing daily operations and maintaining documentation standards to leading strategic initiatives and ensuring alignment with project goals. This delineation of responsibilities is crucial for maintaining the project’s integrity, ensuring quality standards, and fostering a collaborative and flexible environment that responds to the evolving demands of the FinOps community.

### Proposed approach
This document, [FOCUS Roles & Tasks](https://docs.google.com/document/d/1bb7GstMwP2Rn4eA7OX0pb8f6d7R4iwKHZyZCc4gTt2g/edit) contains a first draft of FOCUS Roles, Tasks and Responsibilities that need to be analyzed by the members.

### Github issue or Reference
The document containing the description can be found on FOCUS Google Workspace: FOCUS Groups / Discussion-Docs/ [FOCUS Roles & Tasks](https://docs.google.com/document/d/1bb7GstMwP2Rn4eA7OX0pb8f6d7R4iwKHZyZCc4gTt2g/edit)

### Context
It is important to have a clear definition of the tasks and responsibilities within the group.

**Comment by jpradocueva** [comment]
PR [FOUNDATION#10](https://github.com/FinOps-Open-Cost-and-Usage-Spec/foundation/pull/10)

**Comment by jpradocueva** [comment]
Latest list of Roles vs Tasks: [Roles & Tasks](https://docs.google.com/spreadsheets/d/1FOqX3w9l3IjBtUDRJMLv3AVWk4fNuirReYlN5LZ5rls/edit?gid=0#gid=0)

**Comment by shawnalpay** [comment]
@jpradocueva Now that https://github.com/FinOps-Open-Cost-and-Usage-Spec/foundation/pull/10 was merged, can we close this issue?

**Comment by jpradocueva** [comment]
@shawnalpay, I see. the issue didn't close automatically as the PR was in a different repo.
