### ISSUE TITLE
SKU Properties & Providers alignment

### ISSUE THREAD

**Issue by jpradocueva** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#495]
### Description
This issue was created to assign the following action item:
TF2-#xxx: Michael, Zack, Rupa: Lead the discussion on SKU properties and ensure alignment across providers.

### Proposed approach
> Describe the approach that your group is proposing

### Github issue or Reference
> If the topic is related to a particular work item, reference the Github issue. If its a specification-wide topic, indicate that.

### Context
> Add any context that may help the community think through this and provide useful feedback

**Comment by AWS-ZachErdman** [comment]
https://docs.google.com/document/d/1zPEUZ5L5wf9YAJ63ymW3tyrOFx-krJBB6sf1bHU_oOs/edit

Need input from other providers

**Comment by jpradocueva** [comment]
### Action Items agreed on TF-2, July 17 call:
- [ ] TF2-[#495](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/495) Zach: To draft a more detailed request for use cases involving SKU details and raise the question during the Members meeting.
- [ ] TF2-[#495](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/495) Rob: To engage a practitioner group for input on use cases and queries involving SKU details.

**Comment by AWS-ZachErdman** [comment]
https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/516
