### ISSUE TITLE
[Consistency Review]: Use consistent casing for the word decimal

### ISSUE THREAD

**Issue by udam-f2** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#531]
### Description

There are lots of places where we seem to be mixing up casing for the word decimal. 
"This column MUST be a Decimal within the range of non-negative decimal values,"

### Proposed Approach

It seems it should just use standard casing (only upper case if it's the first word e.g. in the constraint table).

**Comment by jpradocueva** [comment]
@udam-f2, the PR #531 related to this Issue was closed after a call, but the issue was moved to milestone v1.2 and is still open. Can we close this issue? Thanks

**Comment by shawnalpay** [comment]
Discussed in Oct 15 TF1; need to follow up with @udam-f2 to confirm whether we can close.

**Comment by udam-f2** [comment]
Ok to close. Thanks

**Comment by jpradocueva** [comment]
### TF-2 Call Oct 15:
Topic: [#531](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/531) Use consistent casing for the word "decimal"
Discussion Summary: This issue from August 2024 addresses whether the word "decimal" should be consistently capitalized across the specifications. A team member checked the current spec and noted different casings were used. A suggestion was made to keep uppercase for the type "decimal" and lowercase for values.
Resolution: It was generally agreed that the issue could be closed, pending confirmation from the issue's author (Udam). A note was left to seek the author's feedback before officially closing it.
