### ISSUE TITLE
[DISCUSSION]: PricingCategory (Committed or Standard) for commitment discount purchase records

### ISSUE THREAD

**Issue by ijurica** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#532]
### Current PricingCategory definition:

Requirements:
> ...
> * PricingCategory MUST be "Standard" when pricing is predetermined at the agreed upon rate for the [billing account](#glossary:billing-account).
> * PricingCategory MUST be "Committed" when [CommitmentDiscountId](#commitmentdiscountid) is not null.
>
> ...

Allowed values:
> **Standard:** Charges priced at the agreed upon rate for the billing account, including negotiated discounts. This includes any flat rate and volume/tiered pricing but does not include dynamic or commitment discount pricing.
> **Committed:** Charges with reduced prices due to a commitment discount specified by the Commitment Discount ID. 

### Issue

Commitment discount purchase records should be classified as Standard, not Committed. 

### Proposed Approach

Rephrase the following requirement:

> * PricingCategory MUST be "Committed" when [CommitmentDiscountId](#commitmentdiscountid) is not null.

New version:

> * PricingCategory MUST be "Committed" when [CommitmentDiscountId](#commitmentdiscountid) is not null, except when ChargeCategory is "Purchase" and [ResourceId](#resourceid) matches CommitmentDiscountId, representing a charge related to the purchase of that commitment discount.

**Comment by jpradocueva** [comment]
### Action Items from TF-1 call on Aug 27:
- [ ] [TF1-[#532](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/532)] Irena - @ijurica : Update the PR to reflect the agreed changes and submit it for review.
