### ISSUE TITLE
Double Counting (TF-1) 

### ISSUE THREAD

**Issue by ahullah** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#546]
### Documents:
* **Issue**: #[546](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/546) Double Counting
* **Spreadsheet**:  [24.07.21-CommitmentUtilization-sample-datasets](https://docs.google.com/spreadsheets/d/1AYDPZ4rl90PPEbyQJUaGCUSwZ4s_sfy-8sO2KyNq0aM/edit?usp=drive_link)

### Description

Due to Commitment Discounts, the following columns are prone to double counting:

PricingQuantity
ListCost
ContractedCost
CommitmentDiscountQuantity
TODOs:

We didn’t explicitly address this issue in PricingQuantity.
Additionally, I suggest a quick review and alignment of the guidelines across all of these columns.

### Proposed Approach

Spec Review

**Comment by jpradocueva** [comment]
### Action Items from TF-1 call on Sep 24:
- [ ] [TF1-#[546](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/546) ] Alex, @ahullah : Update the PR to use long-form text for aggregation issues and create a separate appendix for data examples.
- [ ] [TF1-#[546](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/546) ] Chris, @cnharris10 : Provide relevant data examples for aggregation issues to be included in the appendix.
