### ISSUE TITLE
Consistency Review: Standardize column specifications for correction charges

### ISSUE THREAD

**Issue by ijurica** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#547]
### Documents:
* **Spreadsheet**: [#547 Corrections](https://docs.google.com/spreadsheets/d/1SvaD-PSzxwRKExKYbQXbtEmVPtbhN4HnycOatvLfGPI/edit?usp=sharing)
* **Folder**:  [#547 Corrections-handling](https://drive.google.com/drive/folders/1iaTEPAOns-A14HAzyqPrAQRm4cw6B8Cu?usp=sharing) (inside of Consistency Review / V1.1 folder)
* **Issue**: [#547](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/547) Consistency Review: Standardize column specifications for correction charges

### Description

Review and align how we specify Corrections across the specification. Address nullability and value ranges of metric columns.

**1. Nullability**

In the case of CommitmentDiscountQuantity, we specified the following:

> … CommitmentDiscountQuantity MAY be negative if ChargeClass is "Correction"….

Meanwhile, for other columns (e.g., costs, quantities, units), we allowed null values for Corrections. For instance:

> … It MUST NOT be null when ChargeClass is not "Correction"…

**2. Value ranges of metric columns**

While we were explicit in CommitmentDiscountQuantity about expecting positive values and allowing negative values for Corrections, we didn’t explicitly address negative values in other metric columns. (We assumed it was understood that quantities and costs can only be negative in the case of Correction charges and must be non-negative for non-Correction charges.)
Briefly discuss whether this should be applied consistently across the specification.

### Proposed Approach

Standardize the specifications, i.e. allow nulls in the case of corrections for all columns except cost metrics, and explicitly define value ranges for all metrics, for the following columns: 

- PricingUnit
- ConsumedUnit
- CommitmentDiscountUnit
- PricingQuantity
- ConsumedQuantity
- CommitmentDiscountQuantity
- ListCost
- ContractedCost
- ListUnitPrice
- ContractedUnitPrice

### GitHub Issue or Reference

Issue #542

**Comment by jpradocueva** [comment]
### Action items from TF-1 call on Sep 24:
- [ ] [TF1-[#547](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/547) ] Irena, @ijurica : Prepare a PR addressing corrections in metric columns, including standardizing null value handling, and submit it for review within 30 hours.
- [ ] [TF1-[#547](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/547) ] Chris, @cnharris10  & Alex, @ahullah: Assist Irena in reviewing the proposed PR before the next members’ meeting.

**Comment by jpradocueva** [comment]
### Comments from Members' call on Oct 31:
**Analysis:** Simple editorial adjustments to normative statements, aimed at improving readability.
**Agreements:** Irena will reintroduce this as part of ongoing editorial work and close [#547](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/547) once a backup is made.
