### ISSUE TITLE
[Proposal] Attribute: Datatype for Decimal/Float values in the data

### ISSUE THREAD

**Issue by rileyjenk** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#67]
### Type
> Attribute

### Proposed Change
> The FOCUS data will include multiple columns that include decimal type data. What level of precision do we need to specify in the spec, do we need to specify?

### Context / Supporting information
>Depending on the item the precision of the value of any record may require high precision decimal values. Determine what level of precision needs to be supported? What are the implications on rounding to the nearest cent for purposes of billing.

**Comment by cnharris10** [comment]
+1

**Comment by udam-f2** [comment]
Numeric format defined in the spec in v1.0
