### ISSUE TITLE
Attribute: Currency code format

### ISSUE THREAD

**Issue by udam-f2** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#75]
Define the the way currency should be specified in FOCUS columns. Provider columns are encouraged to use the same for consistency.

**Comment by mike-finopsorg** [comment]
Discussion in Slack the current thinking is to use
`Decimal / Extended Precision` as the field type and then add a section in Attributes about accuracy of numbers. Explaining the importance of the spec to have accuracy for FinOps.

Related:
https://en.wikipedia.org/wiki/Extended_precision

**Comment by mike-finopsorg** [comment]
In addition when describing the currency that a charge is in aligning to the `code` type in  https://en.wikipedia.org/wiki/ISO_4217 is preferred.

**Comment by udam-f2** [comment]
There may be two things here that need to be defined. One is the billed currency which is necessary for 0.5. The other part of this is 'priced currency' which may match up with the public pricing that's advertised by the provider (e.g. website pricing currency)
