### ISSUE TITLE
Define the casing requirements for IDs and display names

### ISSUE THREAD

**Issue by flanakin** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#87]
### Description
We need to define casing requirements for IDs and display names to ensure they're consistently applied so aggregations are grouped correctly.

### Proposed approach
- IDs should be lowercase.
- Display names should be mixed case and consistently applied (e.g., don't show a name in lowercase in one row, upper in another, and mixed in a third row).

**Comment by udam-f2** [comment]
@flanakin I believe these are defined in the naming convention. Re-open using new template if you think further discussion or work is needed.
