### ISSUE TITLE
Create an appendix for grouping of resources and/or services (Billing Account and Sub/Resource Account)

### ISSUE THREAD

**Issue by ijurica** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#91]
### Type
> Appendix section

### Description
> Need an appendix section that describes various dimensions used for grouping of resources and/or services. Currently, there are 2 constructs used for grouping of resources and/or services. These are Billing Account and Sub/Resource Account. Both are assigned an ID and a Name and thus the billing data contains 4 dimensions - Billing Account ID, Billing Account Name, Sub/Resource Account ID and Sub/Resource Account Name. This appendix section should be linked from all 4 dimensions.

**Comment by amitw-g** [comment]
Also need to add a link to various dimension specs linking to the appendix.
